### ISSUE TITLE
録画処理時のエラーについて

### ISSUE THREAD

**Issue by mage999** [l3tnun/EPGStation#107]
本日インストールして、録画テストをしたのですが、
下記エラーで録画できない状況です。

[2018-06-17T18:28:53.325] [INFO] system - preprec: 60021850853 空飛ぶゆうれい船
[2018-06-17T18:28:53.432] [INFO] system - recording: 60021850853 空飛ぶゆうれい船
[2018-06-17T18:28:53.434] [INFO] system - recording stream: /data1/2018年06月17日17時00分00秒-空飛ぶゆうれい船.ts
[2018-06-17T18:28:58.436] [ERROR] system - recording failed: 60021850853 空飛ぶゆうれい船
[2018-06-17T18:28:58.437] [ERROR] system - preprec failed: 60021850853 空飛ぶゆうれい船
[2018-06-17T18:28:58.437] [ERROR] system - Error: recordingStartError
    at Timeout.setTimeout [as _onTimeout] (/root/EPGStation/dist/server/Model/Operator/Recording/RecordingManageModel.js:273:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

何を修正するばいいのでしょうか？

**Comment by l3tnun** [comment]
他の番組でもそのようになるのでしょうか？
```recording failed``` が発生しているということは Mirakurun からストリームが正しく受けられていないかもしれません。
あと考えられるとすれば録画ディレクトリのアクセス権限が正しく設定されているかくらいですかね。

使用している os, node のバージョン, EPGStation のバージョン等書いていただけると助かります。

**Comment by mage999** [comment]
どの番組でも同様な状況です。

mirakurun　はdockerで動かしていて、
EPGstationの番組表は正常に表示されています。
インストール当初に一度だけ正常に動作いたしました。

CentOS Linux release 7.5.1804 (Core)
node　v8.11.3
EPGStation　0.9.6
になります。

よろしくお願いします。

**Comment by l3tnun** [comment]
番組のライブ視聴は正常に動きますか？

**Comment by mage999** [comment]
androidから実行するとこのリンク先は再生できませんとなります。
dockerのmirakurunからの通信に問題があるですかね…
何か確認するいい方法はありますでしょうか？

**Comment by l3tnun** [comment]
まず Mirakurun から直接視聴できるか確認しましょう。

1. ```http://[mirakurun host ip]:[port]/api/debug``` へアクセスし ```
channels ```  をクリック
2. ```/channels``` をクリックし下部の try it out! をクリックし放送局データを取得する (Response Body に表示されます)
3. 表示された放送局データから現在放映中の番組の ```type, channel, id``` を記憶する

```
  {
    "type": "BS", <--- これ
    "channel": "BS01_1", <--- これ
    "name": "BS:BS01_1",
    "services": [
      {
        "id": 400161,  <--- これ
        "serviceId": 161,
        "networkId": 4,
        "name": "ＢＳ－ＴＢＳ"
      }
    ]
  },
```

4. http://[mirakurun host ip]:[port]/api/channels/{type}/{channel}/services/{id}/stream?decode=1 を VLC 等で開き視聴できるか確認する

上記の例では
```
http://[mirakurun host ip]:[port]/api/channels/BS/BS01_1/services/400161/stream?decode=1
```
となります

この手順で視聴できない場合、まず Mirakurun の設定に問題があります

**Comment by l3tnun** [comment]
ping @mage999

**Comment by mage999** [comment]
すいません、返信遅くなりました。
docker と既存̪̪̺̪bridgeの競合で、mirakurun側に問題があったと判明しました。
現在は問題なく利用できております。
ご対応ありがとうございました。

**Comment by l3tnun** [comment]
解決したようなので閉じます
