### ISSUE TITLE
PostgreSQL使用時、ルール情報更新時にエラーが発生します

### ISSUE THREAD

**Issue by regppe** [l3tnun/EPGStation#108]
Windows環境にPostgreSQLを導入し、それを利用しているのですが、ルール情報の更新時に以下のエラーが発生します。（状況から察するにLinuxでも同様かと思います）
=====
[2018-06-20T10:01:20.662] [ERROR] system - { error: 列"keyregexp"は型booleanですが、式は型integerでした
    at Connection.parseE (C:\Users\xxxxx\epgstation\EPGStation\node_modules\pg\lib\connection.js:553:11)
    at Connection.parseMessage (C:\Users\xxxxx\epgstation\EPGStation\node_modules\pg\lib\connection.js:378:19)
    at Socket.<anonymous> (C:\Users\xxxxx\epgstation\EPGStation\node_modules\pg\lib\connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 208,
  severity: 'ERROR',
  code: '42804',
  detail: undefined,
  hint: '式を書き換えるかキャストしなければなりません',
  position: '80',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '540',
  routine: 'transformAssignedExpr' }
=====
ソース(RolesDB.ts)を確認したところ、Boolean型に対してNumberで更新しているようです。
PostgreSQLでは、Boolean型をNumberで更新できないので、文字型に型キャストする等の対応が必要と思われます。

**Comment by regppe** [comment]
早速の修正、ありがとうございました。
こちらでも動作確認できました。

**Comment by l3tnun** [comment]
確認できたようなので閉じます
