### ISSUE TITLE
【質問】preprec failedの発生について

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#121]
Windows10 home x64
node.js v8.10.0
Mirakurun 2.7.0
EPGStation 0.9.8

いつもお世話になります。
TVRockを停止してからは稀になったものの、未だに`preprec failed`が発生することがあります。
先ほどまた発生しましたので、原因等教えて頂けないでしょうか。

EPGStation-master\logs\Operator\system.log

    [2018-07-07T16:14:56.969] [ERROR] system - preprec failed: 318565734411285 hogefuga
    [2018-07-07T16:14:56.969] [ERROR] system - { Error: socket hang up
        at createHangUpError (_http_client.js:331:15)
        at Socket.socketOnEnd (_http_client.js:423:23)
        at emitNone (events.js:111:20)
        at Socket.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
    [2018-07-07T16:15:01.985] [INFO] system - run: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe &'C:\TV\EPGStation\EPGStationRecErrorMessage.ps1' -mode PrepRecFailed
    [2018-07-07T16:15:02.000] [INFO] system - cancel reserve: 318565734411285
    [2018-07-07T16:15:02.125] [INFO] system - start update (cancel)
    [2018-07-07T16:15:02.125] [INFO] system - update (cancel) done
    [2018-07-07T16:15:08.438] [INFO] system - recording preprec failed process is fin

C:\Users\hoge\AppData\Local\Mirakurun\stdout

    2018-07-07T16:14:53.281+09:00 debug: ProgramItem#318565734421470 (networkId=31856, eventId=21470) has removed for redefine to ProgramItem#318565734421895 (eventId=21895)
    2018-07-07T16:14:56.469+09:00 debug: saving programs...
    2018-07-07T16:14:56.484+09:00 info: save db `C:\Users\cucko\AppData\Local\Mirakurun\programs.json`
    2018-07-07T16:14:57.140+09:00 info: TSFilter has closed (serviceId=57344, eventId=11285)
    2018-07-07T16:14:57.140+09:00 debug: TunerDevice#2 end stream for user `unix:1530947096862` (priority=3)...
    2018-07-07T16:14:57.140+09:00 info: TunerDevice#2 end streaming to user `unix:1530947096862` (priority=3)
    - - GET /api/programs/318565734411285/stream?decode=1 HTTP/1.1 - - - - ms EPGStation/0.9.8 MirakurunClient/2.7.0 Node/v8.10.0 (win32)
    - - GET /api/services HTTP/1.1 200 - - 5.958 ms EPGStation/0.9.8 MirakurunClient/2.7.0 Node/v8.10.0 (win32)
    - - GET /api/programs HTTP/1.1 200 - - 320.196 ms EPGStation/0.9.8 MirakurunClient/2.7.0 Node/v8.10.0 (win32)
    - - GET /api/tuners HTTP/1.1 200 - - 0.472 ms EPGStation/0.9.8 MirakurunClient/2.7.0 Node/v8.10.0 (win32)
    2018-07-07T16:22:46.399+09:00 info: TSFilter has closed (serviceId=null, eventId=null)

C:\Users\hoge\AppData\Local\Mirakurun\stdout(stderrの誤りでした!）には特に記録されていませんでした。
お手数ですがよろしくお願いします。

**Comment by l3tnun** [comment]
EPGStation のログから分かることは Mirakurun との接続が切れたということくらいですかね。
Mirakurun の stderr も貼ってください。

**Comment by cuckoozero** [comment]
パイプ接続で
`"mirakurunPath": "\\\\.\\pipe\\mirakurun",`
となっています。

**Comment by l3tnun** [comment]
なるほど。原因がわからないですね。

私の環境 (Linux) でも同じエラーが発生したことがあるのですが、Mirakurun 側のメモリ使用量を上げたらそれ以降は起きてないです。
デフォルトでは Mirakurun 起動時に ```--max_old_space_size=256 ``` このように設定されていますが、私の環境では 2048 に増やしています。

**Comment by cuckoozero** [comment]
ありがとうございます。
ググったところ、processes.jsonのおっしゃる項目とserver.ymlのhighWaterMarkを修正すると良いようですね。
やってみます！

**Comment by l3tnun** [comment]
```highWaterMark``` の設定はむやみに弄ると不安定になるようなので程々にしてください。

**Comment by l3tnun** [comment]
あと ```processes.json``` は pm2 への登録時に使用されるので windows の場合は関係ないような。

**Comment by cuckoozero** [comment]
[こちら](http://www.nodoka.org/mirakurun-%E3%83%90%E3%83%83%E3%83%95%E3%82%A1-%E6%9E%AF%E6%B8%87%E9%9A%9C%E5%AE%B3-%E5%AF%BE%E7%AD%96%E7%B7%A8/)を参考にして

%AppData%\Roaming\npm\node_modules\mirakurun\package.jsonの`"start.win32": "node.exe --max_old_space_size=256 bin/init.win32.js",`を2048に変更し、

server.ymlに`highWaterMark: 268435456`を追加してみました。

これで再発しないかしばらく様子を見ようと思います。
教えて下さりありがとうございました。
