### ISSUE TITLE
後からエンコードする際のディレクトリ指定

### ISSUE THREAD

**Issue by totemoyoi** [l3tnun/EPGStation#140]
便利に使わせていただいています、度重なるアップデートお疲れ様です。

Windows7環境で使用しているのですが、
録画ファイルを後からエンコードする際に、
・「元ファイルと同じ場所に保存する」をチェックすると
例えば「録画フォルダ/TEMP/ANIME」に元ファイルを保存していたときに、
録画フォルダ内に「/TEMP￥ANIME」という全角￥マークを含むディレクトリが作成され、
その中にエンコード済のファイルが保存されるという現象が起きています。
また、録画予約時のようなエンコード済ファイルの保存先ディレクトリ指定を、後から
エンコード時にも指定できるとありがたいと思っています。

また、全く別の話ですが、ffmpegのQSVがエラーで動作しない環境なので、
encode.jsからQSVEncCを呼び出したく色々試しているのですが、下記の表記だとまだエンコードが完了していないのに開始直後にエラーになってこのようなログが出力されます（実際にはmp4ファイルは出力されません）

■enc.js
```
const spawn = require('child_process').spawn;
const ffmpeg = 'C:\\TS\\EPGStation\\bin\\ffmpeg.exe';
const qsvenc = 'C:\\TS\\remote\\qsv\\QSVEncC\\x64\\QSVEncC64.exe';

let mode = 'main';
if(process.argv.length >= 3 && (process.argv[2] === 'main' || process.argv[2] === 'sub' || process.argv[2] === 'qsv')) {
    mode = process.argv[2];
}

const input = process.env.INPUT;
const output = process.env.OUTPUT;
const videoHeight = parseInt(process.env.VIDEORESOLUTION, 10);

let args;
if(mode === 'qsv'){
    args = ['--audio-copy', '-i', input, '--bluray', '--vbr', '2800', '--maxbitrate', '30000', '-o', output];
} else{
if(videoHeight > 720) {
    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-s', '1280x720', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
} else {
    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
}
}

let child;
if (mode === 'qsv') {
    child = spawn(qsvenc, args);
} else{
    child = spawn(ffmpeg, args);
}

```
■ログ
```
[2018-08-01T13:46:37.108] [INFO] system - push encode: J:\MEDIA\EPGS\20180731_2351_プレマップ.ts 2
[2018-08-01T13:46:37.108] [INFO] system - encode start: J:\MEDIA\EPGS\20180731_2351_プレマップ.ts H264-qsv
[2018-08-01T13:46:37.215] [INFO] system - create new encode child: 1533098797215
[2018-08-01T13:46:45.740] [INFO] system - code { code : 0, signal: null }
[2018-08-01T13:46:45.740] [INFO] system - fin encode: J:\MEDIA\EPGS\20180731_2351_プレマップ.mp4
[2018-08-01T13:46:45.745] [ERROR] system - Error: FileIsNotFound
```

enc.js内の表記についてなんらかアドバイスをいただけないでしょうか？

**Comment by advancedbear** [comment]
totemoyoiさん

enc.jsの方しかコメントできませんが、以前私がrecordedEndCommandから呼び出したNodeスクリプト内でtsselectを起動したときもなぜか実行途中で終了される症状がありました。
私の場合は、`process.execFile` で呼び出したものでしたが、tsselect実行時に出力される進捗が `maxBuffer` から溢れて強制終了されるというものでした。

>maxBuffer <number> Largest amount of data in bytes allowed on stdout or stderr. If exceeded, the child process is terminated. See caveat at maxBuffer and Unicode. **Default: 200 * 1024.**
https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

私の場合はexecFileのオプションとして `{maxBuffer: 4096*1024}` という感じで指定したら動くようになりました。
ただ、上記ページでもspawnの方にはmaxBufferオプションが無いようなのでこれが原因かどうかはわかりません。
試しにffmpegのオプションとして `-loglevel quiet` を追加してみてはいかがでしょうか。

**Comment by l3tnun** [comment]
> 録画フォルダ内に「/TEMP￥ANIME」という全角￥マークを含むディレクトリが作成され、
その中にエンコード済のファイルが保存されるという現象が起きています。

バグですね、修正します。

> また、録画予約時のようなエンコード済ファイルの保存先ディレクトリ指定を、後から
エンコード時にも指定できるとありがたいと思っています。

api では用意しているのですが、Android で表示に問題があり解決できるか不明なため WebUI 上で実装されるかは未定です。

---

エンコードの件ですが、EPGStation に限った話ではなく Node.js で QSVEncC の呼び出しに失敗しているという話なのでこちらから特に何かはありません。

おそらく QSVEncC 側で何らかのエラーは出ていると思いますので、```spawn``` で生成した QSVEncC のプロセスの stdout, stderr をどこかに出力させて見てみると良いかと思います。

あとは WIndows 環境ということなので [これ](https://github.com/l3tnun/EPGStation/issues/87#issuecomment-396120032) のようなユーザー権限の問題かもしれませんね。

**Comment by l3tnun** [comment]
バグ修正、エンコード追加時のディレクトリ指定の追加が完了しました。
ご確認ください。

**Comment by izenizen** [comment]
一旦閉じられてしまったissueをもう一度開けることをお許しください。
Ubuntu 18.04.2で、"recorded": /mnt/sdaに設定しております。
ffmpegは自分でnvencができるようにbuildしたものですが、/usr/local/bin/に設置しており、pathが通っております。(whereis ffmpegで確認済み)
enc.shのffmpegの引数に`-loglevel quiet`も入れてみました。ただ{maxBuffer: 4096*1024}はenc.shのどこに入れればよいか不明でしたので入れておりません。
このよう中、下記のエラーがでてFileIsNotFoundでh264へのコンバートが止まってしまいます。
このエラーは終息したと思っておりましたが、まだ継続しており、どのように直せばよいか、ご意見をいただけませんでしょうか。

`[2019-03-28T13:31:16.884] [INFO] system - push encode: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].ts 0

[2019-03-28T13:31:16.886] [INFO] system - encode start: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].ts H264

[2019-03-28T13:31:16.895] [INFO] system - create new encode child: 1553779876895

[2019-03-28T13:31:16.923] [INFO] system - code { code : 0, signal: null }

[2019-03-28T13:31:16.923] [INFO] system - fin encode: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].mp4

[2019-03-28T13:31:16.926] [ERROR] system - Error: FileIsNotFound

    at EventEmitter.listener.once (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:442:28)

    at Object.onceWrapper (events.js:277:13)

    at EventEmitter.emit (events.js:189:13)

    at IPCClient.<anonymous> (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:45:31)

    at Generator.next (<anonymous>)

    at /home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:7:71

    at new Promise (<anonymous>)

    at __awaiter (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:3:12)

    at process.IPCClient.process.on (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:27:40)

    at process.emit (events.js:189:13)`

**Comment by izenizen** [comment]
一旦閉じられてしまったissueをもう一度開けることをお許しください。
Ubuntu 18.04.2で、"recorded": /mnt/sdaに設定しております。
ffmpegは自分でnvencができるようにbuildしたものですが、/usr/local/bin/に設置しており、pathが通っております。(whereis ffmpegで確認済み)
enc.shのffmpegの引数に-loglevel quietも入れてみました。ただ{maxBuffer: 4096*1024}はenc.shのどこに入れればよいか不明でしたので入れておりません。
このよう中、下記のエラーがでてFileIsNotFoundでh264へのコンバートが止まってしまいます。
このエラーは終息したと思っておりましたが、まだ継続しており、どのように直せばよいか、ご意見をいただけませんでしょうか。

`[2019-03-28T13:31:16.884] [INFO] system - push encode: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].ts 0
[2019-03-28T13:31:16.886] [INFO] system - encode start: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].ts H264
[2019-03-28T13:31:16.895] [INFO] system - create new encode child: 1553779876895
[2019-03-28T13:31:16.923] [INFO] system - code { code : 0, signal: null }
[2019-03-28T13:31:16.923] [INFO] system - fin encode: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].mp4
[2019-03-28T13:31:16.926] [ERROR] system - Error: FileIsNotFound
    at EventEmitter.listener.once (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:442:28)
    at Object.onceWrapper (events.js:277:13)
    at EventEmitter.emit (events.js:189:13)
    at IPCClient.<anonymous> (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:45:31)
    at Generator.next (<anonymous>)
    at /home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:3:12)
    at process.IPCClient.process.on (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:27:40)
    at process.emit (events.js:189:13)`
