### ISSUE TITLE
preprecが1回失敗する

### ISSUE THREAD

**Issue by routeone34** [l3tnun/EPGStation#145]
### 環境
*Version of EPGStation: 1.1.0
*Version of Mirakurun: 2.7.0
*Version of Node: 8.11.3
*Version of NPM: 5.6.0
*OS: Debian Stretch
*Architecture: x64

### Issue
特定の番組（再現条件は不明）で、preprecが1回失敗します。
リトライにより録画開始されるものの、番組冒頭が切れます。

某局で月～木の23:30～24:00の番組を予約録画しています。
8/13（月）が第1話だったのですが、1話目2話目で上記の現象が発生しました。
切り分けになるかと思い、3話ではdropCheckをOFFにしたところ正常でした。

2話目（8/14 23:30）のログを末尾に貼りますが、見た感じのシーケンスでは
23:29:46 preprec開始
23:30:01 recording開始
23:30:06 recordingStartError
23:30:12 preprec開始（2回目）
以下は正常

となっています。1話目も全く同じシーケンスでした。
今夜もう一度dropCheckをONに戻して試してみますが、なんとなくまた起きそうな予感はします。

なお当方いろいろと録画していますが、他の番組ではいまのところ発生していません。
特定の番組のストリーム？が内部的に正常にdropCheckできなかったりするのかなと勝手に考えています。

■epgstationのOperator/system.log
[2018-08-14T23:29:46.124] [INFO] system - preprec: 40014116999 アニメ ナナマル サンバツ 第2問 0.01秒の世界!?
[2018-08-14T23:30:01.499] [INFO] system - recording: 40014116999 アニメ ナナマル サンバツ 第2問 0.01秒の世界!?
[2018-08-14T23:30:01.512] [INFO] system - recording stream: /mnt/FileShare/08_DTV/rec01/Data/20180814_2330_アニメ ナナマ>ル サンバツ 第2問 0．01秒の世界!？.ts
[2018-08-14T23:30:06.815] [ERROR] system - recording failed: 40014116999 アニメ ナナマル サンバツ 第2問 0.01秒の世界!?
[2018-08-14T23:30:06.823] [ERROR] system - preprec failed: 40014116999 アニメ ナナマル サンバツ 第2問 0.01秒の世界!?
[2018-08-14T23:30:06.824] [ERROR] system - Error: recordingStartError
    at RecordingManageModel.<anonymous> (/home/kuwa/EPGStation/dist/server/Model/Operator/Recording/Model/Operator/Recording/RecordingManageModel.ts:371:24)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kuwa/EPGStation/dist/server/Model/Operator/Recording/RecordingManageModel.js:4:58)
    at <anonymous>
[2018-08-14T23:30:12.084] [INFO] system - preprec: 40014116999 アニメ ナナマル サンバツ 第2問 0.01秒の世界!?
[2018-08-14T23:30:15.632] [INFO] system - recording: 40014116999 アニメ ナナマル サンバツ 第2問 0.01秒の世界!?
[2018-08-14T23:30:15.633] [INFO] system - recording stream: /mnt/FileShare/08_DTV/rec01/Data/20180814_2330_アニメ ナナマ>ル サンバツ 第2問 0．01秒の世界!？.ts
[2018-08-14T23:30:15.864] [INFO] system - add recorded: 40014116999 アニメ ナナマル サンバツ 第2問 0.01秒の世界!?

■mirakurunのstdout.log
2018-08-14T23:29:46.291+09:00 info: TSFilter has created (serviceId=141, eventId=16999)
2018-08-14T23:29:46.463+09:00 info: TunerDevice#0 process has spawned by command `recpt1 --device /dev/px4video0 --lnb 0 BS13_0 - -` (pid=9366)
2018-08-14T23:29:46.464+09:00 info: TunerDevice#0 streaming to user `unix:1534256986291` (priority=2)
2018-08-14T23:29:46.505+09:00 info: TunerDevice#0 > using device: /dev/px4video0
LNB = 0V
pid = 9366
2018-08-14T23:29:46.772+09:00 info: TunerDevice#0 > device = /dev/px4video0
2018-08-14T23:29:46.779+09:00 info: TunerDevice#0 > C/N = 17.090128dB
2018-08-14T23:29:46.784+09:00 info: TunerDevice#0 > Recording...
2018-08-14T23:29:49.964+09:00 info: save db `/usr/local/var/db/mirakurun/programs.json`
2018-08-14T23:29:55.982+09:00 info: save db `/usr/local/var/db/mirakurun/programs.json`
2018-08-14T23:30:01.311+09:00 info: TSFilter is now ready for eventId=16999
- - GET /api/programs/40014116999/stream?decode=1 HTTP/1.1 200 - - 15168.136 ms EPGStation/1.1.0 MirakurunClient/2.7.1 Node/v8.11.3 (linux)
2018-08-14T23:30:01.601+09:00 info: TSFilter has closed (serviceId=141, eventId=16999)
2018-08-14T23:30:01.601+09:00 info: TunerDevice#0 end streaming to user `unix:1534256986291` (priority=2)
2018-08-14T23:30:04.075+09:00 info: save db `/usr/local/var/db/mirakurun/programs.json`
2018-08-14T23:30:04.612+09:00 info: TunerDevice#0 > SIGTERM received. cleaning up...
Recorded 18sec
2018-08-14T23:30:04.614+09:00 info: TunerDevice#0 process has closed with exit code=0 by signal `null` (pid=9366)

**Comment by l3tnun** [comment]
報告ありがとうございます
ログを見る限りご指摘の通り dropCheck 周りでストリームが止まりデータが保存されず、```recording failed``` -> ```preprec failed``` となっているのかもしれませんね

こちらの環境でも発生するか確認してみます

**Comment by routeone34** [comment]
ありがとうございます
最悪失敗しても抑えの録画システムが別にあるので試してみます。

masterとfeature-145を共存させてどちらもdropCheck=ONの並行で試すつもりですが
mirakurunは1つなので片側だけpreprec失敗したら変な動きにならないかな？
少し心配ですが抑えはあるのでやってみます。

**Comment by l3tnun** [comment]
preprec で失敗しても EPGStation と Mirakurun 間の接続が切れるだけですので、複数の EPGStation を共存させても問題ないはずです

**Comment by routeone34** [comment]
mirakurunの仕様的にも大丈夫っぽいですね。仮に片側だけpreprec失敗しても録画は続くようです。

とりあえず共存での並列設定はしたので今夜の結果を待ちます。
仮にmasterはNGでfeature-145がOKならわかりやすいですが、この番組で必ず発生する確証もないので案外両方OKになっちゃうかもしれません。その場合はまあ気長に来週も検証しましょう。

**Comment by routeone34** [comment]
結果報告です。
残念ながら（？）、masterもbranch(feature-145)も再現せず問題なしでした。
番組というよりその前のtsストリームの内容による可能性もあり、その場合偶然発生するまで再現しないかもしれません。

一応、過去4回の結果サマリーをまとめておきます。
参考になるかわかりませんが、番組開始直前に流れていた放送内容も書いておきます。

1回目: 8/13 23:30
DropCheck: ON
結果: NG
直前の内容: ルーブル美術展のCM（予備の録画システムから確認）

2回目: 8/14 23:30
DropCheck: ON
結果: NG
直前の内容: 不明

3回目: 8/15 23:30
DropCheck: OFF
結果: OK
直前の内容: 前番組「チルテレ」の末尾

4回目: 8/16 23:30
DropCheck: ON
結果: OK
直前の内容: BS日テレのアイキャッチ（というか番組間に挿入するスポット）

**Comment by routeone34** [comment]
どうも中途半端な状態で申し訳ありません。
その後もBS日テレを半日録画してみたのですが（笑）masterもbranchも再現しませんね。

確実な再現条件がないと調査困難であれば、本issueは再現したときにまた報告ということでcloseでもこちらは構いません。その場合feature-145をmasterにマージされるかどうかはお任せで（そもそもこちらがどうこう言うことではないですね）。

無論そちらの判断でopen継続でも構いません。
今回発生したシリーズ（BS日テレ「ナナマルサンバツ」）はあと2週続きますので、変更箇所の効果が明確になる（＝masterでのみ再現する）のが望ましければ、その期間ならば並列テスト可能です。

**Comment by l3tnun** [comment]
こちらの環境でも特に再現しなかったです
現状何が問題なのか不明で再現性が無いので調査が難しいですね

抑えの録画システムがあるとのことでしたら、その録画システムで録画した現象発生が確認できた 1 話もしくは 2 話の ts ファイルは残っていますか？
もし残っていれば feature-145 ブランチに drop check だけを行うツールを追加したので、そのツールでドロップチェックが正しく行えるか確認していただきたいです

EPGStation をアップデート後、以下のコマンドを実行すると指定した ts ファイルと同じディレクトリに .log ファイルが生成されます

```
node dist/server/TsCheckTool.js /hoge/huga.ts
```

もし止まるようであればさらに原因究明が行えそうですが、そうではないのであれば正直お手上げです

---

> 今回発生したシリーズ（BS日テレ「ナナマルサンバツ」）はあと2週続きますので、変更箇所の効果が明確になる（＝masterでのみ再現する）のが望ましければ、その期間ならば並列テスト可能です。

暫くの間テストしていただけるのであれば助かります
とりあえず issue は open したままで、こちらでも再現するかしばらくテストしてみようと思います

**Comment by routeone34** [comment]
1話のtsは残っていた、というか抑えのシステムはna〇neなのでそこからBD経由でなんとかtsにしました。2話は抑え側で別番組を録画していたので残っていません。

しかし1話のtsにdropCheckツールを試したところ問題なくチェック終了・・・
こうなると現時点の純粋な再現は絶望的ですね。
録画開始時のマージンもEPGStationと異なるでしょうし。ちなみにそのtsでは本編開始前CM部が約11秒でした。

ともあれ長期化も想定してbranch側の環境も整えましたので、しばらくはテストに協力させていただきます。最悪どうにもならなくてもこれまでの発生頻度を考えれば仕方ないと思います。

**Comment by routeone34** [comment]
経過報告です。
現在以下の3環境で並列テストを行っています。

#	ソース		設定
1	master		dropCheck=ON
2	feature-145	dropCheck=ON
3	master		dropCheck=OFF

3環境とも同一mirakurunを使用で、3環境で同じ番組を録画し続けています。
（mirakurun的には1チューナーだけが使われている状態）

本日以下の番組でなぜか[環境2]にだけpreprec失敗が発生しました。
　BS日テレ 8/23 10:00-11:00 日中合作時代劇 蒼穹の昴

末尾にログを貼っておきますが基本的に前回のログと同じです。(1回fail後retryで成功）
ただ今回は録画開始時にmirakurun側のstderrが出ています。確か前回はなかったはず。

また正常録画したtsを環境2のdropCheckツールにかけたところ特に止まらずチェック終了します。
補足情報として、今回の録画先頭内容はアクサダイレクトのCMでした（前回はルーブル美術展）。

環境2だけ、というのは想定外で却って謎が深まったような気がします。事前の想定としては「全環境で発生」「環境1のみ発生」だったので。
こうなるとtsの内容というよりは、うちの環境ということになるのかもしれません。ただdropCheck=OFFの環境では一度も発生がないので、それが発生条件の一つにはなっている気がします。

いずれにせよもう少しテストは継続します。
必要な情報があれば出しますので指示ください。


■EPGStationのsystem.log
==================================================================
[2018-08-23T09:59:45.083] [INFO] system - preprec: 40014117321 日中合作時代劇 蒼穹の昴「第19回 急ぎすぎた改>革」(字幕)
[2018-08-23T10:00:01.235] [INFO] system - recording: 40014117321 日中合作時代劇 蒼穹の昴「第19回 急ぎすぎた>改革」(字幕)
[2018-08-23T10:00:01.237] [INFO] system - recording stream: /mnt/FileShare/08_DTV/rec02/Data/20180823_1000_>日中合作時代劇 蒼穹の昴「第19回 急ぎすぎた改革」(字幕).ts
[2018-08-23T10:00:06.314] [ERROR] system - recording failed: 40014117321 日中合作時代劇 蒼穹の昴「第19回 急>ぎすぎた改革」(字幕)
[2018-08-23T10:00:06.320] [ERROR] system - preprec failed: 40014117321 日中合作時代劇 蒼穹の昴「第19回 急ぎ>すぎた改革」(字幕)
[2018-08-23T10:00:06.321] [ERROR] system - Error: recordingStartError
    at RecordingManageModel.<anonymous> (/home/kuwa/EPGStation/dist/server/Model/Operator/Recording/Model/Operator/Recording/RecordingManageModel.ts:353:24)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kuwa/EPGStation/dist/server/Model/Operator/Recording/RecordingManageModel.js:4:58)
    at <anonymous>
[2018-08-23T10:00:11.564] [INFO] system - preprec: 40014117321 日中合作時代劇 蒼穹の昴「第19回 急ぎすぎた改>革」(字幕)
[2018-08-23T10:00:13.306] [INFO] system - recording: 40014117321 日中合作時代劇 蒼穹の昴「第19回 急ぎすぎた>改革」(字幕)
[2018-08-23T10:00:13.308] [INFO] system - recording stream: /mnt/FileShare/08_DTV/rec02/Data/20180823_1000_>日中合作時代劇 蒼穹の昴「第19回 急ぎすぎた改革」(字幕).ts
[2018-08-23T10:00:13.322] [INFO] system - add recorded: 40014117321 日中合作時代劇 蒼穹の昴「第19回 急ぎすぎた改革」(字幕)
以下正常
==================================================================

■mirakurunのstderr （ログに時刻がないがログファイル日付から8/25 10:00）
==================================================================
error - failed on ARIB_STD_B25::put() : code=-9
Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25)
==================================================================

**Comment by l3tnun** [comment]
feature-145 ブランチで recordingStartError が発生したということは dropCheck 前の段階でエラーが発生したということなので、dropCheck の有無は関係ないですね

Mirakurun のソースと今回の stderr ログから勘案するに、

https://github.com/Chinachu/Mirakurun/blob/d92d6b3c13598c7815b4898ce0bed204118307e5/src/Mirakurun/Tuner.ts#L410-L417

1. EPGStation が Mirakurun にストリームを要求 (preprec)
2. Mirakurun が空きチューナーを探し出して EPGStation に録画可能であるとレスポンスを返す
3. EPGStation の状態が preprec から recording へ移行する
4. Mirakurun はチューナから吐き出されるストリームをチェックし、指定された programId のストリーム開始を確認後デコードを試みるが、デコーダでエラーが発生しストリームが切断される。そのため EPGStation との接続が切れる
5. Mirakurun との接続が切れたため EPGStation 側ではタイムアウトが発生し recordingStartError が起こる
6. EPGStation で retry が発生し 1. に戻るが、デコーダでエラーが発生しないため正常に録画が開始される

このようなことが起きているのではないかと思います

Mirakurun は同じチャンネルであればチューナを共用しますがデコーダプロセスは共有しないので、今回の場合は 3 ストリーム分のデコード処理がほぼ同時に開始されたはずです
その負荷に B-CAS カード or カードリーダが耐えられなかったのではないかと考えられます

アニメ ナナマル サンバツ 1,2 話の場合は Mirakurun の stderr ログについて触れられていないのでわかりませんが、現象がとてもよく似ているので今回と同じことが起きていたのではないかな？と思います

B-CAS カード 1 枚で 8ts 分処理しているなどの話はよく聞きますので通常では問題ない範囲だと思いますが、使用環境によっては変わると思いますので B-CAS カード周りの見直しをしてみてはいかがでしょうか？

---

録画テストの是非ですが今回の feature-145 ブランチでエラーが発生したことで dropCheck 周りが原因ではない判明したので、環境2, 環境3 での検証は不要かなと思います

**Comment by routeone34** [comment]
最初の2回（8/13,14）については並行録画していませんでした。
mirakurunのstderrはなかったはずですが、logrotateがうまくいってないときがたまにあるのでそれで残らなかった可能性もあります。

少なくとも内部動作的にmirakurun側が接続を切ってるのは間違いなさそうなので、BCASカードを含めたうちの環境を再チェックしてみます。

ご協力ありがとうございました。
本件はクローズしていただいて構いません。
