### ISSUE TITLE
PostgreSQLを設定して起動するとエラー

### ISSUE THREAD

**Issue by umlx5h** [l3tnun/EPGStation#196]
### 環境
* Version of EPGStation: `1.2.7`
* Version of Mirakurun: `2.7.5`
* Version of Node: `v10.14.2`
* Version of NPM: `6.4.1`
* OS: mac os x
* Architecture: x64

### Issue
当方のMac環境でもラズパイ(nodev8.14.1)環境でも全く同じエラーが発生しましたが、config.jsonでPostgreSQLの設定をして`npm start`するとエラーが出て起動ができません。  
pgのバージョンを上げてみても全く同じエラーが出ます。 
MySQLやsqlite3は問題ありません。
````
$ npm start

> EPGStation@1.2.7 start ~/EPGStation
> node dist/server/index.js

~/EPGStation/node_modules/pg/lib/connection.js:120
      var eventName = msg.name === 'error' ? 'errorMessage' : msg.name
                          ^

TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (~/EPGStation/node_modules/pg/lib/connection.js:120:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EPGStation@1.2.7 start: `node dist/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EPGStation@1.2.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-12-26T20_46_37_591Z-debug.log
````

~/.npm/_logs/2018-12-26T20_46_37_591Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '~/.nvm/versions/node/v10.14.2/bin/node',
1 verbose cli   '~/.nvm/versions/node/v10.14.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.14.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle EPGStation@1.2.7~prestart: EPGStation@1.2.7
6 info lifecycle EPGStation@1.2.7~start: EPGStation@1.2.7
7 verbose lifecycle EPGStation@1.2.7~start: unsafe-perm in lifecycle true
8 verbose lifecycle EPGStation@1.2.7~start: PATH: ~/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:~/Projects/forked/EPGStation/node_modules/.bin:~/.nvm/versions/node/v10.14.2/bin:~/Library/Android/sdk/platform-tools:~/bin:~/.rbenv/shims:~/Library/Android/sdk/platform-tools:~/bin:~/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle EPGStation@1.2.7~start: CWD: ~/Projects/forked/EPGStation
10 silly lifecycle EPGStation@1.2.7~start: Args: [ '-c', 'node dist/server/index.js' ]
11 silly lifecycle EPGStation@1.2.7~start: Returned: code: 1  signal: null
12 info lifecycle EPGStation@1.2.7~start: Failed to exec start script
13 verbose stack Error: EPGStation@1.2.7 start: `node dist/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (~/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (~/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid EPGStation@1.2.7
15 verbose cwd ~/Projects/forked/EPGStation
16 verbose Darwin 18.2.0
17 verbose argv "~/.nvm/versions/node/v10.14.2/bin/node" "~/.nvm/versions/node/v10.14.2/bin/npm" "start"
18 verbose node v10.14.2
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error EPGStation@1.2.7 start: `node dist/server/index.js`
22 error Exit status 1
23 error Failed at the EPGStation@1.2.7 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

config.jsonは下記のように設定しました。 
```
    "dbType": "postgresql",
    "postgresql": {
        "host": "localhost",
        "port": 3306,
        "user": "epgstation",
        "password": "epgstation",
        "database": "epgstation",
        "connectionTimeoutMillis": 20000,
        "idleTimeoutMillis": 20000
    },
```

**Comment by l3tnun** [comment]
こちらでも確認してみます。
（土日頃になりそう）

**Comment by l3tnun** [comment]
node 8系だと落ちることを確認しました。
修正可能か見てみます

**Comment by l3tnun** [comment]
落ちることを確認できたと思いましたが、こちらの環境設定ミスでした。

macOS, Linux かつ node v8, v10系で動作することが確認できました。
PostgreSQL (v11.1) は docker で用意したものを使用して検証しました。

なにが原因なのか分からないので、PostgreSQL のバージョンを教えていただけると助かります。

**Comment by umlx5h** [comment]
わざわざありがとうございます。
127.0.0.1でも変わりませんでした。
設定はこんな感じです。
```
    "mirakurunPath": "http://192.168.1.160:40772",
    "dbType": "postgresql",
    "postgresql": {
        "host": "127.0.0.1",
        "port": 3306,
        "user": "epgstation",
        "password": "epgstation",
        "database": "epgstation",
        "connectionTimeoutMillis": 20000,
        "idleTimeoutMillis": 20000
    },
```

postgresqlの方はこんな感じです。
```
psql -U epgstation
Password for user epgstation: 
psql (11.1 (Ubuntu 11.1-1.pgdg18.04+1))
Type "help" for help.
epgstation=# \du
 epgstation | Superuser, Create role, Create DB                          | {}
 postgres   | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
epgstation=# \l
 epgstation | epgstation | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres   | postgres   | UTF8     | en_US.UTF-8 | en_US.UTF-8 |

**Comment by l3tnun** [comment]
うーん、原因が分からなくてお手上げですね。
すいません。
他のDBで問題なければそちらを使ってください。

**Comment by umlx5h** [comment]
そうします。
親切に対応していただきありがとうございました。
