### ISSUE TITLE
#140to

### ISSUE THREAD

**Issue by izenizen** [l3tnun/EPGStation#255]
### 環境
* Version of EPGStation: `1.x.x`
* Version of Mirakurun: `2.x.x`
* Version of Node: `v8.x.x`
* Version of NPM: `x.x.x`
* OS:
* Architecture: x64

### Issue
...

**Comment by izenizen** [comment]
環境
Version of EPGStation: 1.4.7
Version of Mirakurun: 2.10.0
Version of Node: v10.15.3
Version of NPM: 6.4.1
OS: Ubuntu 18.04.2
Architecture: x64

一旦閉じられてしまったissueをもう一度開けることをお許しください。
Ubuntu 18.04.2で、"recorded": /mnt/sdaに設定しております。
ffmpegは自分でnvencができるようにbuild(version N-93467-g54655623a8)したものですが、/usr/local/bin/に設置しており、pathが通っております。(whereis ffmpegで確認済み)
enc.shのffmpegの引数に-loglevel quietも入れてみました。ただ{maxBuffer: 4096*1024}はenc.shのどこに入れればよいか不明でしたので入れておりません。
このよう中、下記のエラーがでてFileIsNotFoundでh264へのコンバートが止まってしまいます。
このエラーは終息したと思っておりましたが、まだ継続しており、どのように直せばよいか、ご意見をいただけませんでしょうか。

`[2019-03-28T13:31:16.884] [INFO] system - push encode: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].ts 0

[2019-03-28T13:31:16.886] [INFO] system - encode start: /mnt/sda/2019年03月28日20時45分00秒-首都圏ニュース845[字].ts H264

[2019-03-28T13:31:16.895] [INFO] system - create new encode child: 1553779876895

[2019-03-28T13:31:16.923] [INFO] system - code { code : 0, signal: null }

[2019-03-28T13:31:16.923] [INFO] system - fin encode: /mnt/sda/2019年03月28日20時45分00秒-首都圏
ニュース845[字].mp4

[2019-03-28T13:31:16.926] [ERROR] system - Error: FileIsNotFound
at EventEmitter.listener.once (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:442:28)
at Object.onceWrapper (events.js:277:13)
at EventEmitter.emit (events.js:189:13)
at IPCClient. (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:45:31)
at Generator.next ()
at /home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:7:71
at new Promise ()
at __awaiter (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:3:12)
at process.IPCClient.process.on (/home/hide/epg/EPGStation/dist/server/Model/IPC/IPCClient.js:27:40)
at process.emit (events.js:189:13)`

**Comment by l3tnun** [comment]
まずissueのタイトルですが、意味不明です。

次にエラーについてですが、エンコード時間があまりに短いのでファイルが何も生成されず FileIsNotFound となっているのでしょう。
EPGStationとしては正しい動作です。

そのため #140 には何ら関係なく、ただ単に enc.sh の変更が正しく出来ていないだけです。

> ffmpegの引数に-loglevel quietも入れてみました。

正しく意図が理解できていますか？ffmpegの出力が確認できませんので止めましょう。

https://github.com/l3tnun/EPGStation/blob/master/doc/log-manual.md

ログレベルを debug にし ffmpeg の出力を確認し、ご自身で原因を究明してください。

あと参考ですが docker で nvenc の動作を確認したものが↓になります。

https://github.com/l3tnun/docker-mirakurun-epgstation/blob/nvenc/epgstation/config/enc.sh

**Comment by l3tnun** [comment]
EPGStation の問題では無い為閉じます。
