### ISSUE TITLE
録画終了時のエンコードが失敗する

### ISSUE THREAD

**Issue by Marron0421** [l3tnun/EPGStation#258]
### Issue
...
```
[2019-04-04T22:10:25.650] [INFO] system - create new encode child: 1554383425650
[2019-04-04T22:10:43.539] [INFO] system - push encode: /root/EPGStation/recorded/encode/tv_program/クローズアップ現代+/クローズアップ現代+「ショーケン・独自映像 最期の日々8年の素顔」[字].ts 0
[2019-04-04T22:10:43.544] [INFO] system - encode start: /root/EPGStation/recorded/encode/tv_program/クローズアップ現代+/クローズアップ現代+「ショーケン・独自映像 最期の日々8年の素顔」[字].ts H264
[2019-04-04T22:10:43.551] [INFO] system - create new encode child: 1554383443551
[2019-04-04T22:10:43.557] [INFO] system - code { code : 0, signal: null }
[2019-04-04T22:10:43.557] [INFO] system - fin encode: /root/EPGStation/recorded/encode/tv_program/クローズアップ現代+/クローズアップ現代+「ショーケン・独自映像 最期の日々8年の素顔」[字].mp4
[2019-04-04T22:10:43.559] [ERROR] system - Error: FileIsNotFound
    at EventEmitter.listener.once (/root/EPGStation/dist/server/Model/IPC/IPCClient.js:442:28)
    at Object.onceWrapper (events.js:277:13)
    at EventEmitter.emit (events.js:189:13)
    at IPCClient.<anonymous> (/root/EPGStation/dist/server/Model/IPC/IPCClient.js:45:31)
    at Generator.next (<anonymous>)
    at /root/EPGStation/dist/server/Model/IPC/IPCClient.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/EPGStation/dist/server/Model/IPC/IPCClient.js:3:12)
    at process.IPCClient.process.on (/root/EPGStation/dist/server/Model/IPC/IPCClient.js:27:40)
    at process.emit (events.js:189:13)
```
再起動等試してみましたが、だめでした

**Comment by advancedbear** [comment]
https://github.com/l3tnun/EPGStation/issues/255#issuecomment-477854954

せめてloglevel:debugにしてからffmpegのログも出すとか、enc.jsを改変してるならそれを出すとかしていただきたいところですが。

**Comment by l3tnun** [comment]
advancedbear さんの仰る通りで、情報が少なすぎて何もわかりません。

最近 HLS 再生時に字幕を表示するため下記のオプションを ffmpeg に付けていますので、もしかしたらそれが原因かもしれません。外してみてください。

```
-map 0 -ignore_unknown
```

**Comment by advancedbear** [comment]
@Marron0421 
別にネトストするつもりはありませんが、解決してるならちゃんとIssueをクローズしていただけないですかね？
https://twitter.com/KurimotoYugo/status/1115587758787928064

**Comment by l3tnun** [comment]
@advancedbear 
ありがとうございます。issue のクローズの判断ができるので助かります。

@Marron0421 
advancedbear  さんの言うとおり、解決したら放置しないで何らかのアクションが欲しいです。

**Comment by Marron0421** [comment]
すいません、普段GitHubをあまり見ていませんので応答が遅れてしまいました。
https://twitter.com/KurimotoYugo/status/1115587758787928064
上記のエンコードは自信で作成したシェルスプリクトを使用してエンコードを行っております。
ただ、標準で用意されているエンコードオプションは動作しません。

enc.shの改変は行っておりません。
`-map 0 -ignore_unknown`を外してみましたが、変化はありませんでした。

`せめてloglevel:debugにしてからffmpegのログも出すとか`と、ありますが、デフォルトで用意されているスプリクトはどのようにしてログレベルを変更すればよいのでしょうか？

**Comment by l3tnun** [comment]
> `せめてloglevel:debugにしてからffmpegのログも出すとか`と、ありますが、デフォルトで用意されているスプリクトはどのようにしてログレベルを変更すればよいのでしょうか？

advancedbear さんが一番最初につけてくれたコメントをよく読んでください。
