### ISSUE TITLE
TS削除ができない

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#266]
### 環境
* Version of EPGStation: `1.4.9`
* Version of Mirakurun: `2.10.1`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS:Windows10
* Architecture: x64

### Issue
番組→delete→TS（のみ）にチェック→削除をクリック
すると「ファイルの削除に失敗しました：TS」と出ます。h264だと出ずに消せます。両方同時なら削除はできます。

また、編集から全体を選びTSのみ削除をすると一見正常に消せたように見えて消えていません。

症状が出始めた前後で心当たりがあるのは「一時録画先を追加」した位です。

**Comment by ohmsa** [comment]
録画直後のエンコードはできていますが、録画後しばらくしてTSを元にエンコードするとキューに積みあがりません。

試しに一時録画先の設定を消してみたところTS削除、TS纏めて削除、TSからのエンコードができました。もしかすると一時録画先を設定すると「一時録画先にTSがある」として処理し、録画後しばらくするとそこにTSファイルがないためこのようなエラーが起きるのでしょうか。

**Comment by l3tnun** [comment]
おそらく何らかの原因で recordedTmp から recorded へファイルが移動するときに適切に DB が書き換わっていない or 該当部分の DB 読み出し処理にバグがある事が原因だと思いますが、こちらで症状が再現できません。

> 録画直後のエンコードはできていますが、録画後しばらくしてTSを元にエンコードするとキューに積みあがりません。

録画終了後 recordedTmp から recorded へファイルを移動してからエンコードのキューへ追加されるため、この挙動は大変謎です。

使用しているデータベースの種類, config.json の recorded, recordedTmp  部分の設定がどのようになっているか教えてください。
あと削除する前にTS の再生 or ダウンロードが可能か確認お願いします。正しく DB が書き換えられていない場合はできないはずです。

**Comment by ohmsa** [comment]
config.jsonの各種設定は
"dbType": "mysql",
    "mysql": {
        "host": "127.0.0.1",
        "port": 3306,
        "user": "*****",
        "password": "*****",
        "database": "*****",
        "connectTimeout": 1000,
        "connectionLimit": 10
    },
    "isEnabledDropCheck": true,
    "recorded":"J:\\EPGStation\\DTV",
    "recordedFormat":"%YEAR%%MONTH%%DAY%%HOUR%%MIN%-%TITLE%_%CHNAME%",

です。recordedTempはD:\\DTV_Tempに指定してありました（その設定自体は消してしまいました）。

TSダウンロード試行結果は

{"code":500,"message":"Internal Server Error","errors":"ENOENT: no
such file or directory, stat
'D:\\DTV_Temp\\なんでここに先生が！？\\201904290130-なんでここに先生が!？
4時限目_ＢＳ１１イレブン.m2ts'"}

となっておりました。Temp側にあると思っているようです。


2019年5月4日(土) 18:14 l3tnun <notifications@github.com>:

**Comment by ohmsa** [comment]
config.jsonの各種設定は
"dbType": "mysql",
    "mysql": {
        "host": "127.0.0.1",
        "port": 3306,
        "user": "*****",
        "password": "*****",
        "database": "*****",
        "connectTimeout": 1000,
        "connectionLimit": 10
    },
    "isEnabledDropCheck": true,
    "recorded":"J:\\EPGStation\\DTV",
    "recordedFormat":"%YEAR%%MONTH%%DAY%%HOUR%%MIN%-%TITLE%_%CHNAME%",

です。recordedTempはD:\\DTV_Tempに指定してありました（その設定自体は消してしまいました）。

TSダウンロード試行結果は
{"code":500,"message":"Internal Server Error","errors":"ENOENT: no such file or directory, stat 'D:\\DTV_Temp\\なんでここに先生が！？\\201904290130-なんでここに先生が!？ 4時限目_ＢＳ１１イレブン.m2ts'"}
となっておりました。Temp側にあると思っているようです。

**Comment by l3tnun** [comment]
MySQL環境にて現象の確認しました。
新しいファイルパスの遠録に失敗していますね。

修正します。

**Comment by ohmsa** [comment]
これと関連しているかはわかりませんが、m2tsのアップロードに失敗します。mp4は失敗しません。

2019年5月4日(土) 21:36 l3tnun <notifications@github.com>:

**Comment by l3tnun** [comment]
アップロード失敗時のログがあれば貼ってください。

**Comment by ohmsa** [comment]
初歩的な質問で恐縮ですが、ログの取得方法と言うかアップロード失敗時のログはどのファイルに格納されているのでしょう。

2019年5月4日(土) 21:39 l3tnun <notifications@github.com>:

**Comment by l3tnun** [comment]
Readme を読みましょう

https://github.com/l3tnun/EPGStation#%E3%83%AD%E3%82%B0%E3%81%AE%E7%A2%BA%E8%AA%8D

**Comment by l3tnun** [comment]
fix-266 ブランチにて修正完了しました。
確認お願いします。

**Comment by l3tnun** [comment]
> これと関連しているかはわかりませんが、m2tsのアップロードに失敗します。mp4は失敗しません。

こちらの環境では再現しませんでした。config.json の uploadTempDir でなにか設定をしていますか?

**Comment by ohmsa** [comment]
fix-266にて、一時録画先を指定した状態で昔録画した一時録画先を指定していた時期の録画をDL試みたところ
{"code":500,"message":"Internal Server Error","errors":"ENOENT: no such file or directory, stat 'D:\\DTV_Temp\\八十亀ちゃんかんさつにっき\\201904291440-八十亀ちゃんかんさつにっき #03_ＡＴ－Ｘ.m2ts'"}
と出ました。

uploadTempDirは設定しておりません。

引き続きログをあたってみます。

**Comment by l3tnun** [comment]
過去に録画された番組の修正は行っていないので、手動でDBを修正してください。
おそらくファイル自体は recorded に設定したディレクトリに存在すると思いますので、
Recorded テーブルの isTmp を false とするれば読み込めるはずです。

バグ自体は修正されましたのでマージ後この issue を閉じます。

**Comment by ohmsa** [comment]
もしかすると、この状態でクリーンアップするとtempにあると思われているTSすべて消えてしまうのでしょうか。

**Comment by l3tnun** [comment]
消えますね

**Comment by ohmsa** [comment]
>>アップロード失敗時のログがあれば貼ってください。
operatorsystem.logにて以下のログが見つかりました。
recordedTempはなしの状態です。

[2019-05-05T22:44:00.870] [INFO] system - create new recorded: 11515
[2019-05-05T22:44:30.509] [INFO] system - add external file: 11515
[2019-05-05T22:44:30.509] [INFO] system - rename file data\upload\file-16a883cb4b59cc7 to J:\EPGStation\DTV\201904291440-八十亀ちゃんかんさつにっき #03_ＡＴ－Ｘ.m2ts
[2019-05-05T22:44:30.509] [ERROR] system - rename file error
[2019-05-05T22:44:30.509] [ERROR] system - { Error: EXDEV: cross-device link not permitted, rename 'C:\EPGStation\data\upload\file-16a883cb4b59cc7' -> 'J:\EPGStation\DTV\201904291440-八十亀ちゃんかんさつにっき #03_ＡＴ－Ｘ.m2ts'
  errno: -4037,
  code: 'EXDEV',
  syscall: 'rename',
  path: 'C:\\EPGStation\\data\\upload\\file-16a883cb4b59cc7',
  dest: 'J:\\EPGStation\\DTV\\201904291440-八十亀ちゃんかんさつにっき #03_ＡＴ－Ｘ.m2ts' }
[2019-05-05T22:44:30.509] [INFO] system - move file data\upload\file-16a883cb4b59cc7 to J:\EPGStation\DTV\201904291440-八十亀ちゃんかんさつにっき #03_ＡＴ－Ｘ.m2ts
[2019-05-05T22:44:30.830] [ERROR] system - update ts error
[2019-05-05T22:44:30.830] [ERROR] system - { Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'false' for column 'isTmp' at row 1
    at Query.Sequence._packetToError (C:\EPGStation\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\EPGStation\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\EPGStation\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (C:\EPGStation\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (C:\EPGStation\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\EPGStation\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\EPGStation\node_modules\mysql\lib\Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Protocol._enqueue (C:\EPGStation\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (C:\EPGStation\node_modules\mysql\lib\Connection.js:200:25)
    at getPool.getConnection (C:\EPGStation\dist\server\Model\DB\MySQL\MySQLOperator.js:97:32)
    at Ping.onOperationComplete (C:\EPGStation\node_modules\mysql\lib\Pool.js:110:5)
    at Ping.<anonymous> (C:\EPGStation\node_modules\mysql\lib\Connection.js:502:10)
    at Ping._callback (C:\EPGStation\node_modules\mysql\lib\Connection.js:468:16)
    at Ping.Sequence.end (C:\EPGStation\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Ping.Sequence.OkPacket (C:\EPGStation\node_modules\mysql\lib\protocol\sequences\Sequence.js:92:8)
    at Protocol._parsePacket (C:\EPGStation\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (C:\EPGStation\node_modules\mysql\lib\protocol\Parser.js:76:12)
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage: 'Incorrect integer value: \'false\' for column \'isTmp\' at row 1',
  sqlState: 'HY000',
  index: 0,
  sql: 'update Recorded set recPath = \'201904291440-八十亀ちゃんかんさつにっき #03_ＡＴ－Ｘ.m2ts\', isTmp = \'false\' where id = 11515' }
[2019-05-05T22:44:30.892] [INFO] system - delete recorded file 11515

**Comment by l3tnun** [comment]
あー MySQL のエラーぽいですね。見てみます

**Comment by l3tnun** [comment]
現在の master でも同じ症状は出ますか？

**Comment by ohmsa** [comment]
このログ自体はfix-266で発生したものです。fix-266以降のものについては、帰宅次第調べます。

そちらの環境では再発しない、ということでしょうか。

**Comment by l3tnun** [comment]
ああ、すいません。fix-266ブランチで試したものでしたか。
master と差異はないので大丈夫です。

> そちらの環境では再発しない、ということでしょうか。

しませんね。

**Comment by ohmsa** [comment]
別Windows10環境でEPGStation1.5.0をインストールしようとすると、以下のエラーが出ました。
エラーの内容的にｍｙSQLぽいので報告します（関係なかったら申し訳ありません。）

`PS C:\EPGStation> npm start

> EPGStation@1.5.0 start C:\EPGStation
> node dist/server/index.js

[2019-05-11T21:48:18.153] [WARN] system - reserves.json is not found.
[2019-05-11T21:48:18.517] [INFO] system - ServicesDB created
[2019-05-11T21:48:18.550] [INFO] system - ProgramsDB created
[2019-05-11T21:48:18.579] [INFO] system - RulesDB created
[2019-05-11T21:48:18.616] [INFO] system - RecordedDB created
[2019-05-11T21:48:18.650] [INFO] system - EncodedDB created
[2019-05-11T21:48:18.674] [INFO] system - RecordedHistoryDB created
[2019-05-11T21:48:18.763] [INFO] system - start Updater pid: 16588
[2019-05-11T21:48:20.716] [INFO] system - mirakurun -> services: 34
[2019-05-11T21:48:20.946] [ERROR] system - mirakurun updater failed
[2019-05-11T21:48:20.950] [ERROR] system - { Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xEF\xBC\xAE\xEF\xBC\xA8...' for column 'name' at row 1
    at Query.Sequence._packetToError (C:\EPGStation\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\EPGStation\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\EPGStation\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (C:\EPGStation\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (C:\EPGStation\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\EPGStation\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\EPGStation\node_modules\mysql\lib\Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Protocol._enqueue (C:\EPGStation\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (C:\EPGStation\node_modules\mysql\lib\Connection.js:200:25)
    at Promise (C:\EPGStation\dist\server\Model\DB\MySQL\MySQLOperator.js:173:44)
    at new Promise (<anonymous>)
    at callback (C:\EPGStation\dist\server\Model\DB\MySQL\MySQLOperator.js:172:36)
    at MySQLOperator.<anonymous> (C:\EPGStation\dist\server\Model\DB\DBOperator.js:34:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\EPGStation\dist\server\Model\DB\DBOperator.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage: 'Incorrect string value: \'\\xEF\\xBC\\xAE\\xEF\\xBC\\xA8...\' for column \'name\' at row 1',
  sqlState: 'HY000',
  index: 0,
  sql: 'replace into Services (id, serviceId, networkId, name, remoteControlKeyId, hasLogoData, channelType, channelTypeId, channel, type ) VALUES (3273601024, 1024, 32736, \' ＮＨＫ総合１・東京\', 1, true, \'GR\', 0, \'14\', 1)' }
[2019-05-11T21:48:20.963] [ERROR] system - MirakurunUpdater abort`

**Comment by l3tnun** [comment]
```ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value:``` で調べますと文字コード関係のエラーのようですね。
データベースの文字コードはutf-8になっていますか？

**Comment by l3tnun** [comment]
特に進展がないようなので閉じます
問題があれば再度オープンしてください
