### ISSUE TITLE
一部の番組のみ、録画終了時のエンコードに失敗する

### ISSUE THREAD

**Issue by tsukasa1014** [l3tnun/EPGStation#270]
### 環境
* Version of EPGStation: `1.5.1`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.15.3`
* Version of NPM: `6.9.0`
* OS:CentOS7
* Architecture: x64

### Issue
```
[2019-05-13T09:59:01.131] [INFO] system - push encode: /recorder/[20190513-0951][BSテレ東]太陽と緑の健やかタイム.ts 0
[2019-05-13T09:59:01.133] [INFO] system - encode start: /recorder/[20190513-0951][BSテレ東]太陽と緑の健やかタイム.ts H264
[2019-05-13T09:59:01.141] [INFO] system - create new encode child: 1557709141141
[2019-05-13T09:59:01.243] [DEBUG] system -  -y -analyzeduration 10M -probesize 32M -i /recorder/[20190513-0951][BSテ レ東]太陽と緑の健やかタイム.ts -movflags faststart -map 0 -ignore_unknown -max_muxing_queue_size 1024 -vf yadif,scale=-2:720 -preset veryfast -aspect 16:9 -c:v libx264 -crf 23 -f mp4 -c:a aac -ar 48000 -ab 192k -ac 2 /recorder/[20190513-0951][BSテレ東]太陽と緑の健やかタイム.mp4

[2019-05-13T09:59:01.251] [DEBUG] system - ffmpeg version git-2019-05-07-a0328f0 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --prefix=/usr/local/ffmpeg_build --extra-cflags=-I/usr/local/ffmpeg_build/include --extra-ldflags=-L/usr/local/ffmpeg_build/lib --extra-libs='-lm -lpthread' --bindir=/usr/local/ffmpeg_build/bin --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libtheora --enable-libvpx --enable-libass


[2019-05-13T09:59:01.252] [DEBUG] system -   libavutil      56. 26.101 / 56. 26.101
  libavcodec     58. 52.101 / 58. 52.101
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 50.100 /  7. 50.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100


[2019-05-13T09:59:01.259] [DEBUG] system - [mpeg2video @ 0x47e13c0] Invalid frame dimensions 0x0.


[2019-05-13T09:59:01.299] [DEBUG] system -     Last message repeated 8 times
[mpegts @ 0x47dc6c0] start time for stream 3 is not set in estimate_timings_from_pts


[2019-05-13T09:59:01.300] [DEBUG] system - [mpegts @ 0x47dc6c0] Could not find codec parameters for stream 4 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options


[2019-05-13T09:59:01.300] [DEBUG] system - Input #0, mpegts, from '/recorder/[20190513-0951][BSテレ東]太陽と緑の健や かタイム.ts':
  Duration: 00:08:01.73, start: 47538.957567, bitrate: 16017 kb/s
  Program 171


[2019-05-13T09:59:01.301] [DEBUG] system -     Metadata:
      service_name    : #B#S%F%lEl
      service_provider: #B#S?|???El5~
    Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, bottom first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x110]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 255 kb/s
    Stream #0:2[0x130]: Subtitle: arib_caption (Profile A) ([6][0][0][0] / 0x0006)
    Stream #0:3[0x138]: Data: bin_data ([6][0][0][0] / 0x0006)
    Stream #0:4[0x140]: Unknown: none ([13][0][0][0] / 0x000D)
  Program 172
    Metadata:
      service_name    : #B#S%F%lEl?2
      service_provider: #B#S?|???El5~
  Program 173
    Metadata:
      service_name    : #B#S%F%lEl?3
      service_provider: #B#S?|???El5~
  Program 179
    Metadata:
      service_name    : #B#S%F%lElNW;~
      service_provider: #B#S?|???El5~

  Program 777
    Metadata:
      service_name    : 3t2A>pJs
      service_provider: #B#S?|???El5~
  Program 778
    Metadata:
      service_name    : ??778ch
      service_provider: #B#S?|???El5~


[2019-05-13T09:59:01.301] [DEBUG] system - Automatic encoder selection failed for output stream #0:2. Default encoder for format mp4 (codec none) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:2


[2019-05-13T09:59:01.311] [INFO] system - code { code : 0, signal: null }
[2019-05-13T09:59:01.312] [INFO] system - fin encode: /recorder/[20190513-0951][BSテレ東]太陽と緑の健やかタイム.mp4
[2019-05-13T09:59:01.316] [ERROR] system - Error: FileIsNotFound
    at EventEmitter.listener.once (/home/epgstation/EPGStation/dist/server/Model/IPC/IPCClient.js:442:28)
    at Object.onceWrapper (events.js:277:13)
    at EventEmitter.emit (events.js:189:13)
    at IPCClient.<anonymous> (/home/epgstation/EPGStation/dist/server/Model/IPC/IPCClient.js:45:31)
    at Generator.next (<anonymous>)
    at /home/epgstation/EPGStation/dist/server/Model/IPC/IPCClient.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/epgstation/EPGStation/dist/server/Model/IPC/IPCClient.js:3:12)
    at process.IPCClient.process.on (/home/epgstation/EPGStation/dist/server/Model/IPC/IPCClient.js:27:40)
    at process.emit (events.js:189:13)

```
LogLevelをdebugにして確認したところ、上記のようになっていました。enc.js、enc.shの改変はしていません。
ffmpegは以下を参考にコンパイルしてpathが通っているのを確認しています。
https://www.jifu-labo.net/2015/09/ffmpeg_build/

また、正常にエンコードできる場合のログは以下のようになっていました

```
[2019-05-13T10:14:52.621] [INFO] system - push encode: /recorder/[20190510-0129][テレビ朝日]超人女子戦士 ガリベンガーV.ts 0
[2019-05-13T10:14:52.622] [INFO] system - encode start: /recorder/[20190510-0129][テレビ朝日]超人女子戦士 ガリベンガ ーV.ts H264
[2019-05-13T10:14:52.628] [INFO] system - create new encode child: 1557710092628
[2019-05-13T10:14:52.728] [DEBUG] system -  -y -analyzeduration 10M -probesize 32M -i /recorder/[20190510-0129][テレ ビ朝日]超人女子戦士 ガリベンガーV.ts -movflags faststart -map 0 -ignore_unknown -max_muxing_queue_size 1024 -vf yadif,scale=-2:720 -preset veryfast -aspect 16:9 -c:v libx264 -crf 23 -f mp4 -c:a aac -ar 48000 -ab 192k -ac 2 /recorder/[20190510-0129][テレビ朝日]超人女子戦士 ガリベンガーV(1).mp4

[2019-05-13T10:14:52.737] [DEBUG] system - ffmpeg version git-2019-05-07-a0328f0 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)


[2019-05-13T10:14:52.738] [DEBUG] system -   configuration: --prefix=/usr/local/ffmpeg_build --extra-cflags=-I/usr/local/ffmpeg_build/include --extra-ldflags=-L/usr/local/ffmpeg_build/lib --extra-libs='-lm -lpthread' --bindir=/usr/local/ffmpeg_build/bin --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libtheora --enable-libvpx --enable-libass
  libavutil      56. 26.101 / 56. 26.101
  libavcodec     58. 52.101 / 58. 52.101
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 50.100 /  7. 50.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100


[2019-05-13T10:14:52.746] [DEBUG] system - [mpeg2video @ 0x3fb83c0] Invalid frame dimensions 0x0.


[2019-05-13T10:14:52.889] [DEBUG] system -     Last message repeated 13 times
[mpegts @ 0x3fb36c0] start time for stream 2 is not set in estimate_timings_from_pts


[2019-05-13T10:14:52.890] [DEBUG] system - [mpegts @ 0x3fb36c0] PES packet size mismatch
[mpegts @ 0x3fb36c0] Could not find codec parameters for stream 3 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x3fb36c0]

[2019-05-13T10:14:52.891] [DEBUG] system - Could not find codec parameters for stream 4 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x3fb36c0] Could not find codec parameters for stream 5 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x3fb36c0] Could not find codec parameters for stream 6 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x3fb36c0] Could not find codec parameters for stream 7 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x3fb36c0] Could not find codec parameters for stream 8 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x3fb36c0] Could not find codec parameters for stream 9 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options


[2019-05-13T10:14:52.891] [DEBUG] system - Input #0, mpegts, from '/recorder/[20190510-0129][テレビ朝日]超人女子戦士 ガリベンガーV.ts':
  Duration: 00:30:03.12, start: 68776.960200, bitrate: 15638 kb/s
  Program 1064
    Metadata:
      service_name    : ?|???D+F|

      service_provider:
    Stream #0:0[0x111]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, top first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x112]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 168 kb/s
    Stream #0:2[0x115]: Data: bin_data ([6][0][0][0] / 0x0006)
    Stream #0:3[0x1000]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:4[0x1001]: Unknown: none ([13][0][0][0] / 0x000D)


[2019-05-13T10:14:52.891] [DEBUG] system -     Stream #0:5[0x1002]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:6[0x1005]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:7[0x1006]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:8[0x1003]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:9[0x1004]: Unknown: none ([13][0][0][0] / 0x000D)
  Program 1065
    Metadata:
      service_name    : ?|???D+F|
      service_provider:
  Program 1066
    Metadata:
      service_name    : ?|???D+F|
      service_provider:
  Program 1448
    Metadata:
      service_name    : ?|???D+F|

      service_provider:


[2019-05-13T10:14:52.892] [DEBUG] system - Cannot map stream #0:3 - unsupported type.
Cannot map stream #0:4 - unsupported type.
Cannot map stream #0:5 - unsupported type.
Cannot map stream #0:6 - unsupported type.
Cannot map stream #0:7 - unsupported type.
Cannot map stream #0:8 - unsupported type.
Cannot map stream #0:9 - unsupported type.


[2019-05-13T10:14:52.893] [DEBUG] system - Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
  Stream #0:2 -> #0:2

[2019-05-13T10:14:52.893] [DEBUG] system -  (copy)
Press [q] to stop, [?] for help

[aac @ 0x4000700] Reserved bit set.
[aac @ 0x4000700] invalid band type
Error while decoding stream #0:1: Invalid data found when processing input


[2019-05-13T10:14:52.929] [DEBUG] system - [libx264 @ 0x4003240] using SAR=4/3


[2019-05-13T10:14:52.933] [DEBUG] system - [libx264 @ 0x4003240] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2


[2019-05-13T10:14:52.942] [DEBUG] system - [libx264 @ 0x4003240] profile Progressive High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x4003240] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00


[2019-05-13T10:14:52.943] [DEBUG] system - Output #0, mp4, to '/recorder/[20190510-0129][テレビ朝日]超人女子戦士 ガリベンガーV(1).mp4':
  Metadata:
    encoder         : Lavf58.27.103
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 960x720 [SAR 4:3 DAR 16:9], q=-1--1, 29.97 fps, 30k tbn, 29.97 tbc
    Metadata:
      encoder         : Lavc58.52.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc58.52.101 aac
    Stream #0:2: Data: bin_data (gpmd / 0x646D7067)


[2019-05-13T10:14:53.052] [DEBUG] system - [mp4 @ 0x4001cc0] Timestamps are unset in a packet for stream 2. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly


[2019-05-13T10:14:53.398] [DEBUG] system - frame=   70 fps=0.0 q=29.0 size=       0kB time=00:00:02.21 bitrate=   0.2kbits/s dup=26 drop=0 speed= 4.4x
(略)
[2019-05-13T10:22:36.904] [DEBUG] system - frame=54029 fps=116 q=29.0 size=  322048kB time=00:30:02.45 bitrate=1463.7kbits/s dup=26 drop=0 speed=3.88x

[2019-05-13T10:22:36.953] [DEBUG] system - [mpegts @ 0x3fb36c0] PES packet size mismatch


[2019-05-13T10:22:36.959] [DEBUG] system - [aac @ 0x4000700] TYPE_FIL: Input buffer exhausted before END element found
Error while decoding stream #0:1: Invalid data found when processing input


[2019-05-13T10:22:36.984] [DEBUG] system - [mp4 @ 0x4001cc0] Starting second pass: moving the moov atom to the beginning of the file


[2019-05-13T10:22:37.268] [DEBUG] system - frame=54039 fps=116 q=-1.0 Lsize=  325175kB time=00:30:03.00 bitrate=1477.4kbits/s dup=26 drop=0 speed=3.88x
video:281207kB audio:42000kB subtitle:0kB other streams:35kB global headers:0kB muxing overhead: 0.598054%


[2019-05-13T10:22:37.271] [DEBUG] system - [libx264 @ 0x4003240] frame I:479   Avg QP:20.69  size: 57750
[libx264 @ 0x4003240] frame P:14498 Avg QP:24.97  size: 11131
[libx264 @ 0x4003240] frame B:39062 Avg QP:26.99  size:  2532


[2019-05-13T10:22:37.271] [DEBUG] system - [libx264 @ 0x4003240] consecutive B-frames:  2.7%  2.0%  2.1% 93.2%
[libx264 @ 0x4003240] mb I  I16..4: 32.1% 27.3% 40.6%
[libx264 @ 0x4003240] mb P  I16..4:  5.7%  7.6%  2.6%  P16..4: 18.8%  7.6%  5.1%  0.0%  0.0%    skip:52.7%
[libx264 @ 0x4003240] mb B  I16..4:  0.8%  1.1%  0.2%  B16..8:  8.1%  3.7%  0.6%  direct: 3.8%  skip:81.7%  L0:35.3% L1:43.5% BI:21.2%
[libx264 @ 0x4003240] 8x8 transform intra:45.9% inter:27.6%
[libx264 @ 0x4003240] coded y,uvDC,uvAC intra: 49.3% 53.1% 26.1% inter: 5.5% 5.9% 0.8%
[libx264 @ 0x4003240] i16 v,h,dc,p: 54% 22% 14% 10%
[libx264 @ 0x4003240] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 15% 21%  5%  6%  8%  5%  7%  5%
[libx264 @ 0x4003240] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 16% 12%  6%  8%  9%  6%  8%  6%
[libx264 @ 0x4003240] i8c dc,h,v,p: 51% 18% 25%  6%
[libx264 @ 0x4003240] Weighted P-Frames: Y:1.1% UV:0.5%
[libx264 @ 0x4003240] kb/s:1277.60


[2019-05-13T10:22:37.288] [DEBUG] system - [aac @ 0x40045c0] Qavg: 1798.599


[2019-05-13T10:22:37.297] [INFO] system - code { code : 0, signal: null }
[2019-05-13T10:22:37.297] [INFO] system - fin encode: /recorder/[20190510-0129][テレビ朝日]超人女子戦士 ガリベンガーV(1).mp4
```

**Comment by advancedbear** [comment]
>```
>[2019-05-13T09:59:01.301] [DEBUG] system -     Metadata:
>      service_name    : #B#S%F%lEl
>      service_provider: #B#S?|???El5~
>    Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, bottom first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
>    Stream #0:1[0x110]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 255 kb/s
>    Stream #0:2[0x130]: Subtitle: arib_caption (Profile A) ([6][0][0][0] / 0x0006)
>    Stream #0:3[0x138]: Data: bin_data ([6][0][0][0] / 0x0006)
>    Stream #0:4[0x140]: Unknown: none ([13][0][0][0] / 0x000D)
>```

> ```
> [2019-05-13T09:59:01.301] [DEBUG] system - Automatic encoder selection failed for output stream #0:2. Default encoder for format mp4 (codec none) is probably disabled. Please choose an encoder manually.
> Error selecting an encoder for stream 0:2
> ```

字幕データが起因っぽいのは分かるのですが、いつのバージョンからffmpegって地デジの字幕データを`arib_caption (Profile A)`として解析できるようになったんでしょう……。

デフォルトのenc.js等では、 https://github.com/l3tnun/EPGStation/pull/249 に関連して `-map 0` が指定されますが、ffmpegが地デジに含まれる字幕データをbin_dataではなくSubtitleとして認識するようになった結果、 `-map 0` した上で `-f mp4` と指定すると字幕データをエンコードしてmp4コンテナに収めようとしているように見えます。
ただ、arib_captionをmp4コンテナに収める事のできるエンコーダは、arib_captionを適切にエンコード出来ずにエラー出力されているように見えます。
※mp4コンテナにはmov_text（srt形式）くらいしか入らないはずです。assはmkvなどにしか入らないですよね。

**Comment by advancedbear** [comment]
## 現在の正式リリース版 `4.1.3` 
```
Input #0, mpegts, from 'C:\Temp\test.ts':
  Duration: 00:05:02.97, start: 29125.267678, bitrate: 16056 kb/s
  Program 33840
    Metadata:
      service_name    : ?|0&CN?1
      service_provider:
    Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, top first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x110]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 174 kb/s
    Stream #0:2[0x130]: Data: bin_data ([6][0][0][0] / 0x0006)
    Stream #0:3[0x138]: Data: bin_data ([6][0][0][0] / 0x0006)
    Stream #0:4[0x140]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:5[0x15e]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:6[0x15f]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:7[0x160]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:8[0x161]: Unknown: none ([13][0][0][0] / 0x000D)
```

## Nightly Build版 `20190513-dcc9998`
```
Input #0, mpegts, from 'C:\Temp\test.ts':
  Duration: 00:05:02.97, start: 29125.267678, bitrate: 16056 kb/s
  Program 33840
    Metadata:
      service_name    : ?|ﾆ・0&CN?1
      service_provider:
    Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, top first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x110]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 174 kb/s
    Stream #0:2[0x130]: Subtitle: arib_caption (Profile A) ([6][0][0][0] / 0x0006)
    Stream #0:3[0x138]: Data: bin_data ([6][0][0][0] / 0x0006)
    Stream #0:4[0x140]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:5[0x15e]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:6[0x15f]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:7[0x160]: Unknown: none ([13][0][0][0] / 0x000D)
    Stream #0:8[0x161]: Unknown: none ([13][0][0][0] / 0x000D)
```

[FFmpegのリポジトリにあるChangelog](https://github.com/FFmpeg/FFmpeg/blob/master/Changelog)を見ても、

> version <next>:
> (中略)
> - libaribb24 based ARIB STD-B24 caption support (profiles A and C)

とあるので、次回アップデートから地デジの字幕データはffmpegに正常な字幕データとして認識されそうです。
とすると、`-map 0`してしまうとffmpegはSubtitleをエンコードしようとしますが、ffmpegはmp4へのSubtitle用コーデックを自動指定しないためエラーが返るようになりそうですね。
（いずれにしても、今配布されているNightly Buildではarib_captionのdecoderが含まれていないので、そもそも-f data以外では出力できそうにないですが。）

**Comment by tsukasa1014** [comment]
字幕データが問題とのことだったのでenc.js内の
``Array.prototype.push.apply(args, ['-map', '0', '-ignore_unknown', '-max_muxing_queue_size', [maxMuxingQueueSize,]);``
をコメントアウトすることで正常にエンコードできるようになりました。
解決したので閉じさせていただきます。ありがとうございました。
