### ISSUE TITLE
Node v8のサポート終了

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#318]
# Issue
Node v8は2019年末でEoLとなりました。  
参考：https://github.com/nodejs/Release#end-of-life-releases

実際、Node v8環境でEPGStationを動かそうとした場合に、Dependenciesに含まれているパッケージがNode v8のサポートを終了している影響で正常に動作しません。

<details>
<summary>Node v8.11.3環境で `npm run start` した場合</summary>

``` PowerShell
PS E:\Users\advanced_bear\Documents\EPGStation> node -v
v8.11.3

PS E:\Users\advanced_bear\Documents\EPGStation> npm run start

> EPGStation@1.6.6 start E:\Users\advanced_bear\Documents\EPGStation
> node dist/server/index.js

E:\Users\advanced_bear\Documents\EPGStation\node_modules\fs-extra\lib\mkdirs\make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Users\advanced_bear\Documents\EPGStation\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EPGStation@1.6.6 start: `node dist/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EPGStation@1.6.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\advanced_bear\AppData\Roaming\npm-cache\_logs\2020-03-29T06_03_28_889Z-debug.log
```
</details>

EoL迎えてますし、Readmeやpackage.jsonの対応バージョンもv10以上にしてしまって良い気がします。（というか、する必要があると思います）

**Comment by l3tnun** [comment]
ご指摘ありがとうございます。
確かにそのとおりですね。

node v8 のサポートを削除します。

**Comment by l3tnun** [comment]
node v8 のサポート削除しましたので閉じます。

**Comment by ohmsa** [comment]
ここの掲示板でNew issue建てるときのデフォルトが
* Version of EPGStation: `1.x.x`
* Version of Mirakurun: `2.x.x`
* Version of Node: `v8.x.x`
* Version of NPM: `x.x.x`
* OS:
* Architecture: x64
のままになってますね（細かいかもですが……）
