### ISSUE TITLE
録画開始時に、SQLITE_BUSYで、録画がキャンセルされる。

### ISSUE THREAD

**Issue by hmn2nmh** [l3tnun/EPGStation#364]
### 環境
* Version of EPGStation: `1.7.4`
* Version of Mirakurun: `3.2.0`
* Version of Node: `v12.18.3`
* Version of NPM: `6.14.7`
* OS: Linux raspberrypi 5.4.51-v7
* Architecture: x64

### Issue
すみません、GitHubは初めてで、このような書き込みが適切かどうかも
よくわかりません。もし不適当でしたら、無視いただいて構いません。

昨晩、録画したものをチェックしたら、録画されておらず、
ログ(~/EPGStation/logs/Operator/system.log.-2020-12-26.1)
を見たら、下記の通りでした。SQLITE_BUSYで、Errorとなった模様です。
これの原因、対策等がわかれば教えてください。

[2020-12-26T18:29:46.882] [INFO] system - preprec: 327420107212594 (番組名)
[2020-12-26T18:29:49.799] [INFO] system - start Updater pid: 2749
[2020-12-26T18:29:52.304] [INFO] system - mirakurun -> services: 107
[2020-12-26T18:29:52.510] [INFO] system - insert Services done
[2020-12-26T18:29:59.806] [INFO] system - mirakurun -> programs: 17604
[2020-12-26T18:30:03.124] [INFO] system - recording: 327420107212594 (番組名)
[2020-12-26T18:30:03.126] [INFO] system - recording stream: /mnt/hdd1/rectmp/(番組名).ts
[2020-12-26T18:30:03.139] [INFO] system - add recorded: 327420107212594 (番組名)
[2020-12-26T18:30:04.176] [ERROR] system - add recording error: 327420107212594 (番組名)
[2020-12-26T18:30:04.177] [ERROR] system - [Error: SQLITE_BUSY: database is locked] {
  errno: 5,
  code: 'SQLITE_BUSY'
}
[2020-12-26T18:30:04.191] [ERROR] system - Error: recorded data is not found: 327420107212594
    at RecordingManageModel.<anonymous> (/home/tv/EPGStation/dist/server/Model/Operator/Recording/Model/Operator/Recording/RecordingManageModel.ts:476:23)
    at Generator.next (<anonymous>)
    at /home/tv/EPGStation/dist/server/Model/Operator/Recording/RecordingManageModel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/tv/EPGStation/dist/server/Model/Operator/Recording/RecordingManageModel.js:4:12)
    at RecordingManageModel.recEnd (/home/tv/EPGStation/dist/server/Model/Operator/Recording/RecordingManageModel.js:385:16)
    at RecordingManageModel.<anonymous> (/home/tv/EPGStation/dist/server/Model/Operator/Recording/Model/Operator/Recording/RecordingManageModel.ts:439:32)
    at Generator.throw (<anonymous>)
    at rejected (/home/tv/EPGStation/dist/server/Model/Operator/Recording/RecordingManageModel.js:6:65)
[2020-12-26T18:30:04.503] [INFO] system - cancel reserve: 327420107212594
[2020-12-26T18:30:04.606] [INFO] system - start update (cancel)
[2020-12-26T18:30:04.611] [INFO] system - update (cancel) done
[2020-12-26T18:30:09.976] [INFO] system - insert Programs done.
[2020-12-26T18:30:10.033] [INFO] system - mirakurun -> tuners: 4
[2020-12-26T18:30:10.224] [INFO] system - updater done
[2020-12-26T18:30:10.229] [INFO] system - start updateAll
[2020-12-26T18:30:10.233] [INFO] system - done updateAll

**Comment by tomo0611** [comment]
SQLITE_BUSYは主に複数のプログラムでデータベースを読み書きした時に出るので、

https://qiita.com/kambe0331/items/1eaf2383b39c721e7283

とりあえず、上のリンクの解決方法を `./data/database.db` にしてあげて再起動してみてください。

短期間に複数のデータベースの書き込み処理があると起きる可能性もあるので可能なら推奨されているMySQLかMariaDBに移行することをお勧めします

**Comment by hmn2nmh** [comment]
ありがとうございます。
上記解決方法で直りました。
MySQLが推奨でしたら、そちらに移行するようにします。
