### ISSUE TITLE
Windows10環境にてSQLite拡張機能読み込みでnpm startできない

### ISSUE THREAD

**Issue by okyoou** [l3tnun/EPGStation#467]
### 環境
* Version of EPGStation: `2.2.2`
* Version of Mirakurun: `3.5.0`
* Version of Node: `12.16.1`
* Version of NPM: `6.13.4`
* OS:Windows10
* Architecture: x64

### Issue
config.ymlのsqlite設定からコメントアウトを外し、以下のような記述でnpm startさせようとするとエラーにより失敗してしまいます。
SQLite拡張機能関連部分をコメントアウトしたままであれば正常に稼働し、番組も録画できています。
セットアップマニュアル等を見ながら見様見真似でやっているため、config.ymlの記述が誤っているのか、ビルドしたregexp.dllに原因があるのか分かりません。

**config.yml 該当部分**
```
dbtype: sqlite
  sqlite:
   extensions:
    - 'C:/_SQLite3/regexp.dll'
   regexp: true
```

**エラー内容**
```
> epgstation@2.2.2 start C:\EPGStation
> node dist/index.js

initialize error
YAMLException: bad indentation of a mapping entry (5:9)

 2 | mirakurunPath: http://localhost:40772
 3 |
 4 | dbtype: sqlite
 5 |   sqlite:
-------------^
 6 |    extensions:
 7 |     - 'C:/_SQLite3/regexp.dll'
    at generateError (C:\EPGStation\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (C:\EPGStation\node_modules\js-yaml\lib\loader.js:187:9)
    at readBlockMapping (C:\EPGStation\node_modules\js-yaml\lib\loader.js:1182:7)
    at composeNode (C:\EPGStation\node_modules\js-yaml\lib\loader.js:1441:12)
    at readDocument (C:\EPGStation\node_modules\js-yaml\lib\loader.js:1625:3)
    at loadDocuments (C:\EPGStation\node_modules\js-yaml\lib\loader.js:1688:5)
    at Object.load (C:\EPGStation\node_modules\js-yaml\lib\loader.js:1714:19)
    at Configuration.readConfig (C:\EPGStation\dist\model\model\Configuration.ts:55:50)
    at new Configuration (C:\EPGStation\dist\model\model\Configuration.ts:23:14)
    at _createInstance (C:\EPGStation\node_modules\inversify\lib\resolution\instantiation.js:29:12) {
  name: 'YAMLException',
  reason: 'bad indentation of a mapping entry',
  mark: {
    name: null,
    buffer: 'port: 8888\n' +
      'mirakurunPath: http://localhost:40772\n' +
      '\n' +
      'dbtype: sqlite\n' +
      '  sqlite:\n' +
      '   extensions:\n' +
      "    - 'C:/_SQLite3/regexp.dll'\n" +
      '   regexp: true\n' +
      '\n' +
      'epgUpdateIntervalTime: 10\n' +
      '\n' +
      'conflictPriority: 1\n' +
      'recPriority: 2\n' +
      '\n' +
      "recordedFormat: '[%SHORTYEAR%%MONTH%%DAY%]%TITLE% (%CHNAME%)'\n" +
      'recordedFileExtension: .m2ts\n' +
      'recorded:\n' +
      '    - name: recorded\n' +
      "      path: 'F:\\\\Rec\\\\EPGStation'\n" +
      '\n' +
      "thumbnail: '%ROOT%/thumbnail'\n" +
      'thumbnailSize: 480x270\n' +
      'thumbnailPosition: 5\n' +
      '\n' +
      "ffmpeg: 'C:\\\\ffmpeg\\\\ffmpeg.exe'\n" +
      "ffprobe: 'C:\\\\ffmpeg\\\\ffprobe.exe'\n" +
      '\n' +
      'encodeProcessNum: 4\n' +
      'concurrentEncodeNum: 1\n' +
      'encode:\n' +
      '    - name: H.264\n' +
      "      cmd: '%NODE% %ROOT%/config/enc.js'\n" +
      '      suffix: .mp4\n' +
      '      rate: 4.0\n' +
      '\n' +
      'urlscheme:\n' +
      '    m2ts:\n' +
      '        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL://ADDRESS\n' +
      '        android: intent://ADDRESS#Intent;package=org.videolan.vlc;type=video;scheme=PROTOCOL;end\n' +
      '    video:\n' +
      '        ios: infuse://x-callback-url/play?url=PROTOCOL://ADDRESS\n' +
      '        android: intent://ADDRESS#Intent;package=com.mxtech.videoplayer.pro;type=video;scheme=PROTOCOL;end\n' +
      '    download:\n' +
      '        ios: vlc-x-callback://x-callback-url/download?url=PROTOCOL://ADDRESS&filename=FILENAME\n' +
      '\n' +
      'stream:\n' +
      '    live:\n' +
      '        ts:\n' +
      '            m2ts:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2\n" +
      "                      -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast -y -f mpegts pipe:1'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2\n" +
      "                      -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -preset veryfast -y -f mpegts pipe:1'\n" +
      '                - name: 無変換\n' +
      '\n' +
      '            webm:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 3 -c:a libvorbis -ar 48000 -b:a 192k -ac\n" +
      '                      2 -c:v libvpx-vp9 -vf yadif,scale=-2:720 -b:v 3000k -deadline realtime -speed 4 -cpu-used -8 -y -f\n' +
      "                      webm pipe:1'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 2 -c:a libvorbis -ar 48000 -b:a 128k -ac\n" +
      '                      2 -c:v libvpx-vp9 -vf yadif,scale=-2:480 -b:v 1500k -deadline realtime -speed 4 -cpu-used -8 -y -f\n' +
      "                      webm pipe:1'\n" +
      '\n' +
      '            mp4:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2\n" +
      '                      -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune\n' +
      '                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4\n' +
      "                      pipe:1'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2\n" +
      '                      -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune\n' +
      '                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4\n' +
      "                      pipe:1'\n" +
      '\n' +
      '            hls:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -ignore_unknown -max_muxing_queue_size\n" +
      '                      1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1 -hls_segment_filename\n' +
      '                      %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a aac -ar 48000 -b:a 192k\n' +
      '                      -ac 2 -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast -flags +loop-global_header\n' +
      "                      %OUTPUT%'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -ignore_unknown -max_muxing_queue_size\n" +
      '                      1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1 -hls_segment_filename\n' +
      '                      %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a aac -ar 48000 -b:a 128k\n' +
      '                      -ac 2 -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -preset veryfast -flags +loop-global_header\n' +
      "                      %OUTPUT%'\n" +
      '\n' +
      '    recorded:\n' +
      '        ts:\n' +
      '            webm:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3 -c:a libvorbis -ar 48000 -b:a 192k -ac 2\n" +
      '                      -c:v libvpx-vp9 -vf yadif,scale=-2:720 -b:v 3000k -deadline realtime -speed 4 -cpu-used -8 -y -f\n' +
      "                      webm pipe:1'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3 -c:a libvorbis -ar 48000 -b:a 128k -ac 2\n" +
      '                      -c:v libvpx-vp9 -vf yadif,scale=-2:480 -b:v 1500k -deadline realtime -speed 4 -cpu-used -8 -y -f\n' +
      "                      webm pipe:1'\n" +
      '\n' +
      '            mp4:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v\n" +
      '                      libx264 -vf yadif,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune\n' +
      '                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4\n' +
      "                      pipe:1'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2 -c:v\n" +
      '                      libx264 -vf yadif,scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune\n' +
      '                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4\n' +
      "                      pipe:1'\n" +
      '\n' +
      '            hls:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 -ignore_unknown -max_muxing_queue_size\n" +
      '                      1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1 -hls_segment_filename\n' +
      '                      %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a aac -ar 48000 -b:a 192k\n' +
      '                      -ac 2 -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast -flags +loop-global_header\n' +
      "                      %OUTPUT%'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 -ignore_unknown -max_muxing_queue_size\n" +
      '                      1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1 -hls_segment_filename\n' +
      '                      %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a aac -ar 48000 -b:a 128k\n' +
      '                      -ac 2 -c:v libx264 -vf yadif,scale=-2:480 -b:v 3000k -preset veryfast -flags +loop-global_header\n' +
      "                      %OUTPUT%'\n" +
      '\n' +
      '        encoded:\n' +
      '            webm:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 3 -c:a libvorbis -ar 48000 -b:a\n" +
      '                      192k -ac 2 -c:v libvpx-vp9 -vf scale=-2:720 -b:v 3000k -deadline realtime -speed 4 -cpu-used -8 -y\n' +
      "                      -f webm pipe:1'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 3 -c:a libvorbis -ar 48000 -b:a\n" +
      '                      128k -ac 2 -c:v libvpx-vp9 -vf scale=-2:480 -b:v 1500k -deadline realtime -speed 4 -cpu-used -8 -y\n' +
      "                      -f webm pipe:1'\n" +
      '\n' +
      '            mp4:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac\n" +
      '                      2 -c:v libx264 -vf scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune\n' +
      '                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4\n' +
      "                      pipe:1'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac\n" +
      '                      2 -c:v libx264 -vf scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune\n' +
      '                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4\n' +
      "                      pipe:1'\n" +
      '\n' +
      '            hls:\n' +
      '                - name: 720p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown\n" +
      '                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1\n' +
      '                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a\n' +
      '                      aac -ar 48000 -b:a 192k -ac 2 -c:v libx264 -vf scale=-2:720 -b:v 3000k -preset veryfast -flags\n' +
      "                      +loop-global_header %OUTPUT%'\n" +
      '                - name: 480p\n' +
      '                  cmd:\n' +
      "                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown\n" +
      '                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1\n' +
      '                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a\n' +
      '                      aac -ar 48000 -b:a 128k -ac 2 -c:v libx264 -vf scale=-2:480 -b:v 3000k -preset veryfast -flags\n' +
      "                      +loop-global_header %OUTPUT%'\n",
    position: 73,
    line: 4,
    column: 8,
    snippet: ' 2 | mirakurunPath: http://localhost:40772\n' +
      ' 3 | \n' +
      ' 4 | dbtype: sqlite\n' +
      ' 5 |   sqlite:\n' +
      '-------------^\n' +
      ' 6 |    extensions:\n' +
      " 7 |     - 'C:/_SQLite3/regexp.dll'"
  },
  message: 'bad indentation of a mapping entry (5:9)\n' +
    '\n' +
    ' 2 | mirakurunPath: http://localhost:40772\n' +
    ' 3 | \n' +
    ' 4 | dbtype: sqlite\n' +
    ' 5 |   sqlite:\n' +
    '-------------^\n' +
    ' 6 |    extensions:\n' +
    " 7 |     - 'C:/_SQLite3/regexp.dll'"
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epgstation@2.2.2 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epgstation@2.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Okyoou\AppData\Roaming\npm-cache\_logs\2021-05-08T02_01_42_008Z-debug.log
```

**Comment by revelation1048** [comment]
パッとみた感じですが、config.ymlの記載が誤っているように見えます
`sqlite`のインデントが深すぎるかと思います。

以下のようにしてみるとどうでしょうか
```json
dbtype: sqlite
sqlite:
  extensions:
    - '/hoge/regexp.dylib'
  regexp: true
```

**Comment by revelation1048** [comment]
修正が必要な部分は、config.ymlのインデントの深さとなります
たとえはdbtypeとsqliteは同じ階層になる必要があり、2行目のところは先頭の空白文字は不要になります

**Comment by okyoou** [comment]
ありがとうございます。
ご指摘の通り2行目の空白を除去したところregexp.dllが読み込まれ、エラー内容が下記のように変化しました。

```
> epgstation@2.2.2 start C:\EPGStation
> node dist/index.js

[2021-05-08T11:51:27.514] [INFO] system - config.yml read success
[2021-05-08T11:51:27.529] [INFO] system - check mirakurun
[2021-05-08T11:51:27.568] [INFO] system - check db
[2021-05-08T11:51:27.784] [INFO] system - load extension: C:/_SQLite3/regexp.dylib
[2021-05-08T11:51:27.785] [ERROR] system - failed to load extension: C:/_SQLite3/regexp.dylib
[2021-05-08T11:51:28.788] [INFO] system - check db
[2021-05-08T11:51:28.827] [INFO] system - start service pid: 9912
[2021-05-08T11:51:28.830] [INFO] system - start recordings cleanup
[2021-05-08T11:51:28.841] [INFO] system - finish recordings cleanup
[2021-05-08T11:51:28.842] [INFO] system - start reserves cleanup
[2021-05-08T11:51:28.857] [INFO] system - finish reserves cleanup
[2021-05-08T11:51:28.867] [INFO] system - start epg updater pid: 7608
[2021-05-08T11:51:30.077] [FATAL] system - epg updater is disconnected
[2021-05-08T11:51:30.087] [INFO] system - start epg updater pid: 12240
[2021-05-08T11:51:31.376] [FATAL] system - epg updater is disconnected
[2021-05-08T11:51:31.385] [INFO] system - start epg updater pid: 8716
[2021-05-08T11:51:32.582] [FATAL] system - epg updater is disconnected
[2021-05-08T11:51:32.590] [INFO] system - start epg updater pid: 11320
[2021-05-08T11:51:33.755] [FATAL] system - epg updater is disconnected
[2021-05-08T11:51:33.763] [INFO] system - start epg updater pid: 7292
以下 pid: n のみ変化し繰り返し
```
