### ISSUE TITLE
Windows 10環境でのストリーミングと再生ができません。

### ISSUE THREAD

**Issue by taro7611** [l3tnun/EPGStation#469]
### 環境
* Version of EPGStation: `2.2.1`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.1 LTS`
* Version of NPM: `x.x.x`
* OS: `Windows 10 Home 20H2`
* Architecture: x64

### Issue

大変便利なソフトありがとうございます。doc/windows.mdに従ってEPGStationをセットアップしました。番組表の取得や録画は問題なくできるのですが、webでのストリーミングや録画ファイルの再生ができません。

`config.yml`は以下のようにsampleからmirakrunとffmpegのパスのみ変更しています。

**port: 8888

mirakurunPath: 'http://localhost:40772'

dbtype: sqlite

epgUpdateIntervalTime: 10

conflictPriority: 1
recPriority: 2

recordedFormat: '%YEAR%年%MONTH%月%DAY%日%HOUR%時%MIN%分%SEC%秒-%TITLE%'
recordedFileExtension: .m2ts
recorded:
    - name: recorded
      path: '%ROOT%/recorded'

thumbnail: '%ROOT%/thumbnail'
thumbnailSize: 480x270
thumbnailPosition: 5

ffmpeg: 'C:\ffmpeg\ffmpeg.exe'
ffprobe: 'C:\ffmpeg\ffprobe.exe''**

`system.log`は以下のような感じです。

[2021-05-09T17:39:42.350] [INFO] stream - start stream: 0
[2021-05-09T17:39:42.351] [INFO] stream - delete all hls files: 0
[2021-05-09T17:39:42.405] [INFO] stream - create file stream: C:\Users\taros\EPGStation\recorded\2021年05月08日00時20分00秒-タモリ倶楽部[字].m2ts
[2021-05-09T17:39:42.406] [ERROR] stream - create file stream error
[2021-05-09T17:39:42.406] [ERROR] stream - RangeError [ERR_OUT_OF_RANGE]: The value of "start" is out of range. It must be an integer. Received NaN
    at new ReadStream (internal/fs/streams.js:99:5)
    at Object.createReadStream (fs.js:2003:10)
    at RecordedHLSStreamModel.setFileStream (C:\Users\taros\EPGStation\dist\model\service\stream\base\model\service\stream\base\RecordedStreamBaseModel.ts:259:34)
    at RecordedHLSStreamModel.<anonymous> (C:\Users\taros\EPGStation\dist\model\service\stream\base\model\service\stream\base\RecordedStreamBaseModel.ts:85:18)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\taros\EPGStation\dist\model\service\stream\base\RecordedStreamBaseModel.js:36:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_OUT_OF_RANGE'
}
[2021-05-09T17:39:42.407] [INFO] stream - delete all hls files: 0
[2021-05-09T17:39:42.407] [ERROR] stream - start stream error
[2021-05-09T17:39:42.407] [ERROR] stream - Error: FileStreamSetError
    at RecordedHLSStreamModel.<anonymous> (C:\Users\taros\EPGStation\dist\model\service\stream\base\model\service\stream\base\RecordedStreamBaseModel.ts:90:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\taros\EPGStation\dist\model\service\stream\base\RecordedStreamBaseModel.js:36:58)
[2021-05-09T17:39:42.408] [INFO] stream - delete all hls files: 0
[2021-05-09T17:39:42.408] [INFO] stream - stop stream 0

解決方法がわからず困っています。
アドバイスを頂けたら嬉しいです。

**Comment by l3tnun** [comment]
ffmpeg, ffprobe で指定しているパス区切り文字が間違っています。

```\``` ではなく ```\\``` です。

https://github.com/l3tnun/EPGStation/blob/master/doc/windows-setup.md#%E3%83%91%E3%82%B9%E5%90%8D%E5%8C%BA%E5%88%87%E3%82%8A%E6%96%87%E5%AD%97

**Comment by taro7611** [comment]
コメントありがとうございます。
記載した、config.ymlは間違えであり（試行錯誤していたものを貼り付けてしまいました。）

ffmpeg: 'C:\\ffmpeg\\ffmpeg.exe'
ffprobe: 'C:\\ffmpeg\\ffprobe.exe'

で試してみましたがうまくいきませんでした。

状況的に、エンコード .m2ts→H264は途中で止まってしまうができる（同じ時間で止まる）。
放送中番組のストリーミング再生はできない。H264のエンコード済みのストリーミング再生はできる。録画済みの.m2tsのストリーミング再生はできない。

という状況です。
再生できないときはブラウザで黒枠がでますが円が回ったままで再生が始まりません。

情報が間違えていたり小出しだったりですすみません。
なにか原因は考えられるでしょうか？

**Comment by l3tnun** [comment]
```ffmpeg: 'C:\ffmpeg\ffmpeg.exe'```

ではなく

```ffmpeg: 'C:\\ffmpeg\\ffmpeg.exe'```

このようにしてください

**Comment by taro7611** [comment]
`ffmpeg: 'C:\\ffmpeg\\ffmpeg.exe'`
`ffprobe: 'C:\\ffmpeg\\ffprobe.exe'`

Preview確認しないで投稿してしまって大変申し訳ありません。
上記のように設定していますがうまくいきません。

**Comment by l3tnun** [comment]
まず、ライブ視聴は動作しているでしょうか？
動作していないのであれば。下記を参考に ```ffmpeg``` のログを表示させ、原因を追ってください。

https://github.com/l3tnun/EPGStation/blob/master/doc/log-manual.md#%E5%87%BA%E5%8A%9B%E3%83%AC%E3%83%99%E3%83%AB%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%99%E3%82%8B


次に ```ffprobe``` は正しく動作するものが指定できているでしょうか？

> ```
> [2021-05-09T17:39:42.406] [ERROR] stream - create file stream error
> ```

このエラーから録画のストリーミング再生のストリーム生成に失敗した事がわかりますが、
おそらく ```ffprobe``` を使用したビデオ情報取得に失敗しているのではないかと思います。

```http://epgstation-url/api/debug``` にアクセスして ```Swagger UI``` を開き、```/videos/{videoFileId}/duration``` から正常な結果が取得できるか確認してください。

```Swagger UI``` 使用前に下記の設定が必要になると思います。
https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#apiservers
