### ISSUE TITLE
【バグ】あるルールから録画除外した番組を別ルールで録画するとファイルが分割されてしまう

### ISSUE THREAD

**Issue by tomo0611** [l3tnun/EPGStation#517]
## 概要

特定のルールから録画除外した番組を別ルールで録画するとファイルが分割され、さらに欠けるものが発生する。

## 環境

* Version of EPGStation: `v2.6.7`
* Version of Mirakurun: `v3.8.0`
* Version of Node: `v14.17.2`
* Version of NPM: `v7.20.5`
* OS: `Ubuntu Server 20.04.2 LTS (Linux 5.4.0-80)`
* Architecture: `x64`

## 詳細

普段、複数局のアニメを一括で録画してEPG情報を削るエンコードを実施していたが、MBS毎日放送の【アニメイズム】で字幕があることに気づき、生のTSファイルがほしいと思った。

なのでまず、` カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字] `を除外してから、別のルールで予約をした。

![image](https://user-images.githubusercontent.com/31959526/129434399-85e82ae7-2de6-4f72-9da9-e4909b29b0ad.png)

ちゃんと予約画面にも出ていたので安心していたが、実際には下の写真のように分割して録画されていた。

![Screenshot_20210814-133421_Chrome_Canary~2](https://user-images.githubusercontent.com/31959526/129434317-546491f9-590d-4656-b5af-4da360d65328.png)

## 放送時間と録画終了時刻

放送時間は02:25~02:55

録画ファイルはそれぞれ、02:30、02:40、02:49、02:55に録画終了となっていた。

## TSファイル

1つ目と2つ目が欠けている模様

![image](https://user-images.githubusercontent.com/31959526/129434952-a3710dcf-dcc2-441c-9a74-441ef1d7f0e5.png)

## ログ (Operator、長くなってごめんなさい! 一部省略してます)

```
[2021-08-14T02:24:45.004] [INFO] system - preprec: 5781
[2021-08-14T02:25:01.060] [INFO] system - recording: 5781 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts
[2021-08-14T02:25:01.078] [INFO] system - add drop log file: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts.log
[2021-08-14T02:25:01.102] [INFO] system - add recorded 5781 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts
[2021-08-14T02:25:01.125] [INFO] system - recording added reserveId: 5781, recordedId: 5403
[2021-08-14T02:25:01.126] [INFO] system - create video file: カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts
[2021-08-14T02:25:01.144] [INFO] system - set stream.finished: reserveId: 5781 recordedId: 5403
[2021-08-14T02:25:02.478] [INFO] system - stop recording: 5781
[2021-08-14T02:25:02.488] [ERROR] system - RecordingStreamCreator stream error: 5781
[2021-08-14T02:25:02.489] [ERROR] system - drop log check stream error: /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts
[2021-08-14T02:25:02.489] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts.log
[2021-08-14T02:25:02.498] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts.log
[2021-08-14T02:25:02.498] [ERROR] system - recording end error reserveId: 5781 recordedId: 5403
[2021-08-14T02:25:02.499] [ERROR] system - Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:117:38)
    at IncomingMessage.emit (events.js:387:35)
    at Socket.socketCloseListener (_http_client.js:432:11)
    at Socket.emit (events.js:387:35)
    at Pipe.<anonymous> (net.js:675:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
[2021-08-14T02:25:02.501] [INFO] system - start recEnd reserveId: 5781 recordedId: 5403
[2021-08-14T02:25:02.501] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts.log
[2021-08-14T02:25:02.501] [INFO] system - remove recording flag: 5403
[2021-08-14T02:25:02.560] [INFO] system - recording finish: 5781 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].ts
[2021-08-14T02:25:02.709] [INFO] system - preprec: 5781
[2021-08-14T02:25:02.972] [ERROR] system - canceled preprec: 5781
[2021-08-14T02:25:02.989] [ERROR] system - RecordingStreamCreator stream error: 5781
[2021-08-14T02:25:03.163] [INFO] system - create thumbnail: 13600, /home/tomochan/EPGStationV2/thumbnail/5403.jpg
[2021-08-14T02:25:03.647] [INFO] system - add video file: 5403 カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字].m2ts
[2021-08-14T02:29:28.282] [INFO] system - preprec: 5782
[2021-08-14T02:29:30.007] [INFO] system - recording: 5782 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts
[2021-08-14T02:29:30.037] [INFO] system - add drop log file: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts.log
[2021-08-14T02:29:30.078] [INFO] system - add recorded 5782 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts
[2021-08-14T02:29:30.101] [INFO] system - recording added reserveId: 5782, recordedId: 5404
[2021-08-14T02:29:30.102] [INFO] system - create video file: カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts
[2021-08-14T02:29:30.115] [INFO] system - set stream.finished: reserveId: 5782 recordedId: 5404
[2021-08-14T02:30:04.267] [INFO] system - stop recording: 5782
[2021-08-14T02:30:04.287] [ERROR] system - RecordingStreamCreator stream error: 5782
[2021-08-14T02:30:04.289] [ERROR] system - drop log check stream error: /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts
[2021-08-14T02:30:04.296] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts.log
[2021-08-14T02:30:04.331] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts.log
[2021-08-14T02:30:04.337] [ERROR] system - recording end error reserveId: 5782 recordedId: 5404
[2021-08-14T02:30:04.338] [ERROR] system - Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:117:38)
    at IncomingMessage.emit (events.js:387:35)
    at Socket.socketCloseListener (_http_client.js:432:11)
    at Socket.emit (events.js:387:35)
    at Pipe.<anonymous> (net.js:675:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
[2021-08-14T02:30:04.341] [INFO] system - start recEnd reserveId: 5782 recordedId: 5404
[2021-08-14T02:30:04.347] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts.log
[2021-08-14T02:30:04.348] [INFO] system - remove recording flag: 5404
[2021-08-14T02:30:04.462] [INFO] system - update file size: 13603
[2021-08-14T02:30:04.464] [INFO] system - { recordedId: 5404, error: 0, drop: 0, scrambling: 0 }
[2021-08-14T02:30:04.501] [INFO] system - add thumbnail queue: 13603
[2021-08-14T02:30:04.502] [INFO] system - recording finish: 5782 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).ts
[2021-08-14T02:30:04.677] [INFO] system - set timer: 5782, 0
[2021-08-14T02:30:04.701] [INFO] system - preprec: 5782
[2021-08-14T02:30:04.905] [INFO] system - create thumbnail: 13598, /home/tomochan/EPGStationV2/thumbnail/5402.jpg
[2021-08-14T02:30:05.109] [ERROR] system - canceled preprec: 5782
[2021-08-14T02:30:05.124] [ERROR] system - RecordingStreamCreator stream error: 5782
[2021-08-14T02:30:05.951] [INFO] system - create thumbnail: 13603, /home/tomochan/EPGStationV2/thumbnail/5404.jpg
[2021-08-14T02:30:07.311] [INFO] system - add video file: 5404 カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](1).m2ts
[2021-08-14T02:40:08.414] [INFO] system - set timer: 5783, 0
[2021-08-14T02:40:08.423] [INFO] system - preprec: 5783
[2021-08-14T02:40:10.029] [INFO] system - recording: 5783 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](2).ts
[2021-08-14T02:40:10.045] [INFO] system - add drop log file: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](2).ts.log
[2021-08-14T02:40:10.067] [INFO] system - add recorded 5783 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](2).ts
[2021-08-14T02:40:10.104] [INFO] system - recording added reserveId: 5783, recordedId: 5406
[2021-08-14T02:40:10.105] [INFO] system - create video file: カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](2).ts
[2021-08-14T02:40:10.122] [INFO] system - set stream.finished: reserveId: 5783 recordedId: 5406
[2021-08-14T02:49:36.709] [INFO] system - stop recording: 5783
[2021-08-14T02:49:36.715] [INFO] system - start recEnd reserveId: 5783 recordedId: 5406
[2021-08-14T02:49:36.717] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](2).ts.log
[2021-08-14T02:49:36.722] [INFO] system - remove recording flag: 5406
[2021-08-14T02:49:36.746] [INFO] system - update rule reservation: 9
[2021-08-14T02:49:36.784] [INFO] system - update file size: 13607
[2021-08-14T02:49:36.789] [INFO] system - { recordedId: 5406, error: 0, drop: 0, scrambling: 0 }
[2021-08-14T02:49:36.830] [INFO] system - add thumbnail queue: 13607
[2021-08-14T02:49:36.832] [INFO] system - recording finish: 5783 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](2).ts
[2021-08-14T02:49:37.371] [INFO] system - create thumbnail: 13607, /home/tomochan/EPGStationV2/thumbnail/5406.jpg
[2021-08-14T02:49:38.123] [INFO] system - set timer: 5784, 0
[2021-08-14T02:49:38.125] [INFO] system - preprec: 5784
[2021-08-14T02:49:38.147] [INFO] system - all reservation update finish
[2021-08-14T02:49:38.968] [INFO] system - recording: 5784 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](3).ts
[2021-08-14T02:49:38.978] [INFO] system - add drop log file: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](3).ts.log
[2021-08-14T02:49:38.994] [INFO] system - add recorded 5784 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](3).ts
[2021-08-14T02:49:39.013] [INFO] system - recording added reserveId: 5784, recordedId: 5407
[2021-08-14T02:49:39.013] [INFO] system - create video file: カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](3).ts
[2021-08-14T02:49:39.031] [INFO] system - set stream.finished: reserveId: 5784 recordedId: 5407
[2021-08-14T02:49:51.182] [INFO] system - add video file: 5406 カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](2).m2ts
[2021-08-14T02:55:01.999] [INFO] system - start recEnd reserveId: 5784 recordedId: 5407
[2021-08-14T02:55:02.001] [INFO] system - stop drop check: /home/tomochan/EPGStationV2/drop/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](3).ts.log
[2021-08-14T02:55:02.005] [INFO] system - remove recording flag: 5407
[2021-08-14T02:55:02.105] [INFO] system - update file size: 13608
[2021-08-14T02:55:02.110] [INFO] system - { recordedId: 5407, error: 0, drop: 0, scrambling: 0 }
[2021-08-14T02:55:02.144] [INFO] system - add recorded history: 5407
[2021-08-14T02:55:02.188] [INFO] system - add thumbnail queue: 13608
[2021-08-14T02:55:02.189] [INFO] system - recording finish: 5784 /home/tomochan/Videos/カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](3).ts
[2021-08-14T02:55:02.677] [INFO] system - create thumbnail: 13608, /home/tomochan/EPGStationV2/thumbnail/5407.jpg
[2021-08-14T02:55:11.226] [INFO] system - add video file: 5407 カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字](3).m2ts
```

**Comment by l3tnun** [comment]
報告ありがとうございます。

何が起きているか並べてみると以下のようなことが発生しているようですね。

```
[02:24:45.004] reserveId: 5781 が録画開始
[02:25:02.478] reserveId: 5781 が何らかの要因でキャンセル
[02:25:02.498] reserveId: 5781 が Mirakurun からのストリームを停止する際にエラーを検知
[02:25:02.709] reserveId: 5781 が上記エラー検知により録画の retry 開始
[02:25:02.972] reserveId: 5781 の録画準備ができたが、reserveId: 5781の予約情報が削除されていたためキャンセル 
                          (このときも Mirakurun のストリーム停止時にエラーを検知)
[02:29:28.282] reserveId: 5782 が録画開始
[02:30:04.267] reserveId: 5782 が何らかの要因でキャンセル
[02:30:04.337] reserveId: 5782 が Mirakurun からのストリームを停止する際にエラーを検知
[02:30:04.701] reserveId: 5782 が上記エラー検知により録画の retry 開始
[02:30:05.109] reserveId: 5782 の録画準備ができたが、reserveId: 5781の予約情報が削除されていたためキャンセル
[02:40:08.423] reserveId: 5783 が録画開始
[02:49:36.709] reserveId: 5783 が何らかの要因でキャンセル
[02:49:38.123] reserveId: 5784 が録画開始
[02:55:02.189] reserveId: 5784 が正常終了
```

ファイルが分割された要因は予約が3回キャンセルされた事なのですが、なぜ3回もキャンセルが発生したかが謎です。
予約情報の更新の影響を受けてこのようなことが起きたのだと思います。

> ログ (Operator、長くなってごめんなさい! 一部省略してます)

おそらくログが見やすいようにルール更新時のログなどを削除しているかと思いますが、残っていたりしますでしょうか？
残っているのであればログが見てみたいです。
ただ、キャンセルの要因がログに残っていないのでログを頂いても原因が分からないかもしれません。
そのため、ログの出力を強化したものをこれからリリースしますので、そちらで様子を見てもらえますでしょうか。

---

こちらの環境で再現確認ができなかったので、今回使用したルールについて以下の情報を提供していただきたいです。

1. ルールの詳細
    キーワード「アニメイズム】」のルール(以下ルールA)と、 `カノジョも彼女 #07「彼女たちのチャレンジ」【アニメイズム】[字]` を予約するためのルール(以下ルールB)の2つがあると思いますが、ルールの検索オプションを確認したいです。
    ルール編集ページのスクショで問題ないかと思います
2. 各ルールのid
    ルールAとルールBの ruleId を確認したいです。
    各ルールの編集ページに移動した際にブラウザ URL が `http://epgstation_ip:port/#/search?rule=XX` のようになりますが、`XX`の部分が id になります。

**Comment by l3tnun** [comment]
ログ出力を強化した version 2.6.8 をリリースしました。
こちらで様子を見ていただけると助かります。

**Comment by tomo0611** [comment]
ありがとうございます
v2.6.8入れさせていただきました。
本日放送の`アニメ ぼくたちのリメイク 第6.5話 総集編@BS日テレ`で同じことをやってみます。

![image](https://user-images.githubusercontent.com/31959526/129441877-23431a28-4c45-496f-8696-70f97816a6cb.png)


#  1. ルールの詳細
![image](https://user-images.githubusercontent.com/31959526/129440303-86328b2f-5996-4dfe-a906-9de056bd8a69.png)

![image](https://user-images.githubusercontent.com/31959526/129441681-41aae379-e835-4049-8927-1a035f7f1359.png)

# 2. ruleId

`1. ルールB`
`34. ルールA`

**Comment by l3tnun** [comment]
返信ありがとうございます。
確認よろしくおねがいします。
こちらでも再現するか確認してみます。

**Comment by l3tnun** [comment]
こちらの環境でも再現できました。
どうやら予約周りの不具合のようですね。
epgstation は定期的にルールの更新を行っていますが、ルールBとルールAの予約の更新が正しくできていませんでした。
ルールは古い順(=ruleId が若い順)に更新されるので、以下のようなことが起きていると思われます。

1. ルールBの更新
2. ルールBのスキップされた番組がルールAによって予約されているので、ルールAの予約が削除される
3. 予約が削除されたことにより録画が停止する
4. ルールAの更新
5. 削除された予約が復活し、録画が開始される 

修正しますので、しばしお待ち下さい。

**Comment by l3tnun** [comment]
version 2.6.9 にて修正完了しました。
予約情報を生成時の重複チェックで ProgramId で一括にして重複評価を行っていたことが原因でした。

この修正に伴い、以下のような場合に手動予約とルール予約が重複する場合が存在するようになりますが、
重複して予約されるだけで実害はないと思われるのでそのままにします。

1. ProgramId A の番組を手動で予約する
2. ProgramId A の番組を含むルールを作成 & 有効化する
3. ProgramId A の番組の予約が手動予約とルール予約の両方で重複してしまう
    (version 2.6.8 以前までは、ルールでの予約は行われない)
    ※ 1. と 2. の手順が逆の場合は手動予約が弾かれる

**Comment by tomo0611** [comment]
対応ありがとうございます。
v2.6.9インストールしました
早速やって見るので問題なければこのissue閉じさせていただきます

**Comment by tomo0611** [comment]
バッチリでした！！ありがとうございました！！

**Comment by l3tnun** [comment]
確認ありがとうございました。
