### ISSUE TITLE
録画が終わったがエンコード処理が走らない

### ISSUE THREAD

**Issue by takosan-jp** [l3tnun/EPGStation#519]
### 環境
* Version of EPGStation: `2.6.10`
* Version of Mirakurun: `3.8.0`
* Version of Node: 16.6.2`
* Version of NPM: `7.20.3`
* OS: linux
* Architecture: x64

お世話になります。
久しぶりにEPGStationをv1からv2に上げてv1からの移行(予約等)も正常に移行できたのですが、
録画後のEncodeが正常に開始されません。
設定等はあっているような気がするのですが、あまりLinuxは得意ではないため、エラーの詳細が読めません。
何かヒントでもいただければと思います。
以下、encodelogです。
------------------------------------------------------------------------
[2021-08-17T19:05:53.067] [INFO] encode - add new encode: 8
[2021-08-17T19:05:53.088] [INFO] encode - encode start. mode: H.264 name: やさしいニュース１ file: /recorded/やさしいニュース１-20210817_1644.m2ts -> /recorded/やさしいニュース１-20210817_1644(3).mp4
[2021-08-17T19:05:53.088] [INFO] encode - encodeId: 8
[2021-08-17T19:05:53.088] [INFO] encode - encodeCmd.suffix: .mp4
[2021-08-17T19:05:53.088] [INFO] encode - queueItem.directory: undefined
[2021-08-17T19:05:53.088] [INFO] encode - outputFilePath: /recorded/やさしいニュース１-20210817_1644(3).mp4
[2021-08-17T19:05:53.089] [ERROR] encode - build process error: %NODE% %ROOT%/config/enc.js
[2021-08-17T19:05:53.089] [ERROR] encode - create encode process failed
[2021-08-17T19:05:53.089] [ERROR] encode - Error: CmdBinIsNotFound
    at Object.ProcessUtil.parseCmdStr (/root/EPGStation/dist/util/util/ProcessUtil.ts:64:19)
    at EncodeProcessManageModel.buildProcess (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:192:32)
    at EncodeProcessManageModel.<anonymous> (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:59:40)
    at Generator.next (<anonymous>)
    at /root/EPGStation/dist/model/service/encode/EncodeProcessManageModel.js:39:71
    at new Promise (<anonymous>)
    at __awaiter (/root/EPGStation/dist/model/service/encode/EncodeProcessManageModel.js:35:12)
    at Promise (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:35:68)
    at new Promise (<anonymous>)
    at EncodeProcessManageModel.create (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:35:16)
[2021-08-17T19:05:53.090] [ERROR] encode - create encode process error: 8
[2021-08-17T19:05:53.090] [ERROR] encode - Error: CmdBinIsNotFound
    at Object.ProcessUtil.parseCmdStr (/root/EPGStation/dist/util/util/ProcessUtil.ts:64:19)
    at EncodeProcessManageModel.buildProcess (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:192:32)
    at EncodeProcessManageModel.<anonymous> (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:59:40)
    at Generator.next (<anonymous>)
    at /root/EPGStation/dist/model/service/encode/EncodeProcessManageModel.js:39:71
    at new Promise (<anonymous>)
    at __awaiter (/root/EPGStation/dist/model/service/encode/EncodeProcessManageModel.js:35:12)
    at Promise (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:35:68)
    at new Promise (<anonymous>)
    at EncodeProcessManageModel.create (/root/EPGStation/dist/model/service/encode/model/service/encode/EncodeProcessManageModel.ts:35:16)

**Comment by takosan-jp** [comment]
すみません、自己解決いたしました。
申し訳ございません。
