### ISSUE TITLE
録画が正常に開始されず、また保存された録画データとdbの読み込みに失敗している

### ISSUE THREAD

**Issue by MicotoTisaki** [l3tnun/EPGStation#587]
### 環境
* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.7.1`
* Version of Node: `14.15.1`
* OS:Ubuntu20.04
* Architecture: x64
* docker-composeを用いて環境構築を行っております。dbはmysqlを使用しています。

### Issue
...
予約は正常に入るのですが、録画が開始されない番組がある・録画時間を過ぎ録画が終了したタイミングで一瞬録画済みタブにデータは追加されるのですが、その後録画済みから消えてしまうといった現象が発生しています。
現状録画済みには特に規則性が見つからない34個の録画データのみが閲覧できるといった状態になっています。最近までは録画済みタブには今まで録画していたデータが残っておりました。
また、recordedに設定しているフォルダ内を直接確認すると録画データは残っているためdb側で何かしら発生している可能性が考えられますが、どのようにエラーを確認すれば良いのかが分からず、お助けいただけると幸いです。
現状以下の画像の順のように、一部正常に終了し録画データが追加された後に時間がたつと消えてしまうといった状態になっています。
![2](https://user-images.githubusercontent.com/32149435/160092061-39f0af8a-d906-456d-8a56-4428546539b8.PNG)
![3](https://user-images.githubusercontent.com/32149435/160092077-c64d9198-cc49-4c2c-a5d5-3b82a79e705f.PNG)

以下エラーログを添付します。
>/Operator/system.log
[2022-03-25T18:18:48.945] [INFO] system - { insert: 0, update: 1, delete: 0 }
[2022-03-25T18:18:48.955] [INFO] system - successful cancel reservation: 404145
[2022-03-25T18:18:48.955] [DEBUG] system - update recording: 404145
[2022-03-25T18:18:48.955] [INFO] system - cancel recording by skip or overlap reserveId: 404145, recordedId: 160234
[2022-03-25T18:18:48.955] [INFO] system - recording cancel reserveId: 404145, recordedId: 160234, isPlanToDelete: false
[2022-03-25T18:18:48.956] [INFO] system - stop recording: 404145
[2022-03-25T18:18:48.956] [INFO] system - update reocrded: 160234
[2022-03-25T18:19:45.000] [INFO] system - preprec: 404147
[2022-03-25T18:19:48.684] [INFO] system - run storage limit cmd: remove
[2022-03-25T18:19:48.685] [ERROR] system - limit cmd error: remove
[2022-03-25T18:19:48.685] [ERROR] system - Error: CmdBinIsNotFound
    at Object.ProcessUtil.parseCmdStr (/app/dist/util/util/ProcessUtil.ts:64:19)
    at StorageManageModel.<anonymous> (/app/dist/model/operator/storage/model/operator/storage/StorageManageModel.ts:97:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/model/operator/storage/StorageManageModel.js:17:58)
[2022-03-25T18:19:48.690] [INFO] system - name: recorded, free: 71617.65625, threshold: 71680
[2022-03-25T18:19:48.706] [INFO] system - storage limit remove recorded: 160235
[2022-03-25T18:19:48.707] [INFO] system - delete recorded: 160235
[2022-03-25T18:19:48.715] [INFO] system - cancel recording by recorded manager reserveId: [object Object] recordedId: 160235
[2022-03-25T18:19:48.715] [INFO] system - cancel recording reserveId: 404146, isPlanToDelete: true
[2022-03-25T18:19:48.716] [INFO] system - recording cancel reserveId: 404146, recordedId: 160235, isPlanToDelete: true
[2022-03-25T18:19:48.716] [INFO] system - stop recording: 404146
[2022-03-25T18:19:48.718] [DEBUG] system - delete stream: 404146
[2022-03-25T18:19:48.719] [INFO] system - start recEnd reserveId: 404146 recordedId: 160235
[2022-03-25T18:19:48.720] [INFO] system - stop drop check: /app/drop/2022年03月25日18時10分00秒-アニメ　忍たま乱太郎「胸を張れの段」[字].m2ts.log
[2022-03-25T18:19:48.721] [INFO] system - plan to delete reserveId: 404146 recordedId: 160235
[2022-03-25T18:19:48.721] [INFO] system - stop drop check: /app/drop/2022年03月25日18時10分00秒-アニメ　忍たま乱太郎「胸を張れの段」[字].m2ts.log
[2022-03-25T18:19:48.724] [INFO] system - delete: /app/recorded/2022年03月25日18時10分00秒-アニメ　忍たま乱太郎「胸を張れの段」[字].m2ts
[2022-03-25T18:19:48.845] [INFO] system - delete: /app/drop/2022年03月25日18時10分00秒-アニメ　忍たま乱太郎「胸を張れの段」[字].m2ts.log
[2022-03-25T18:19:48.882] [INFO] system - successful delete recorded: 160235
[2022-03-25T18:19:48.885] [INFO] system - cancel reservation: 404146
[2022-03-25T18:19:48.933] [DEBUG] system - --------------------
[2022-03-25T18:19:48.933] [DEBUG] system - { name: '首都圏ネットワーク▽反戦訴える写真の撮影会・東京都千代田区[字]', ruleId: 81 }
[2022-03-25T18:19:48.933] [DEBUG] system - --------------------
[2022-03-25T18:19:48.934] [INFO] system - { insert: 0, update: 1, delete: 0 }
[2022-03-25T18:19:48.945] [INFO] system - successful cancel reservation: 404146
[2022-03-25T18:19:48.945] [DEBUG] system - update recording: 404146
[2022-03-25T18:19:48.945] [INFO] system - cancel recording by skip or overlap reserveId: 404146, recordedId: 160235
[2022-03-25T18:19:48.945] [INFO] system - recording cancel reserveId: 404146, recordedId: 160235, isPlanToDelete: false
[2022-03-25T18:19:48.945] [INFO] system - stop recording: 404146
[2022-03-25T18:19:48.945] [INFO] system - update reocrded: 160235

>/EPGUpdater/system.log
[2022-03-25T17:20:54.564] [INFO] system - update db
[2022-03-25T17:20:58.874] [INFO] system - update db done
[2022-03-25T17:20:58.875] [INFO] system - delete old programs
[2022-03-25T17:29:55.449] [INFO] system - config.yml read success
[2022-03-25T17:29:55.452] [INFO] system - start EPG update
[2022-03-25T17:29:55.452] [INFO] system - start get stream
[2022-03-25T17:29:55.456] [INFO] system - get service
[2022-03-25T17:29:55.472] [INFO] system - start update channel
[2022-03-25T17:29:55.629] [INFO] system - done update channel
[2022-03-25T17:29:55.629] [INFO] system - get programs
[2022-03-25T17:29:55.776] [INFO] system - done get programs
[2022-03-25T17:29:55.779] [INFO] system - start update programs
[2022-03-25T17:29:58.543] [INFO] system - done update programs
[2022-03-25T17:39:58.597] [INFO] system - start save service
[2022-03-25T17:39:58.598] [INFO] system - { insertValues: 0, updateValues: 30 }
[2022-03-25T17:39:58.599] [INFO] system - update db
[2022-03-25T17:39:58.631] [INFO] system - update db done
[2022-03-25T17:39:58.631] [INFO] system - start save program
[2022-03-25T17:39:58.658] [INFO] system - { deleteValues: 0, insertValues: 0, updateValues: 7803 }
[2022-03-25T17:39:58.658] [INFO] system - update db
[2022-03-25T17:40:03.338] [INFO] system - update db done
[2022-03-25T17:40:03.340] [INFO] system - delete old programs
[2022-03-25T17:49:58.605] [INFO] system - start save service
[2022-03-25T17:49:58.605] [INFO] system - { insertValues: 0, updateValues: 14 }
[2022-03-25T17:49:58.607] [INFO] system - update db
[2022-03-25T17:49:58.622] [INFO] system - update db done
[2022-03-25T17:49:58.622] [INFO] system - start save program
[2022-03-25T17:49:58.635] [INFO] system - { deleteValues: 0, insertValues: 0, updateValues: 5306 }
[2022-03-25T17:49:58.635] [INFO] system - update db
[2022-03-25T17:50:01.337] [INFO] system - update db done
[2022-03-25T17:50:01.337] [INFO] system - delete old programs
[2022-03-25T17:59:58.600] [INFO] system - start save service
[2022-03-25T17:59:58.600] [INFO] system - { insertValues: 0, updateValues: 46 }
[2022-03-25T17:59:58.602] [INFO] system - update db
[2022-03-25T17:59:58.691] [INFO] system - update db done
[2022-03-25T17:59:58.691] [INFO] system - start save program
[2022-03-25T17:59:58.734] [INFO] system - { deleteValues: 0, insertValues: 0, updateValues: 8579 }
[2022-03-25T17:59:58.735] [INFO] system - update db
[2022-03-25T18:00:04.591] [INFO] system - update db done
[2022-03-25T18:00:04.592] [INFO] system - delete old programs

>/Service/system.log
[2022-03-25T17:29:49.177] [INFO] system - config.yml read success
[2022-03-25T17:29:51.252] [INFO] system - SocketIO Server has started.
[2022-03-25T17:29:51.252] [INFO] system - http server listening on 8888

よろしくお願いします。

**Comment by MicotoTisaki** [comment]
お世話になっております。少々調べた結果、録画済みから保護をかけたデータのみが生き残っていた様です。それ以外はm2tsファイルの存在は残っているのですが、録画済みからは閲覧ができないといった状態になっている様です。

**Comment by soltune** [comment]
ログを見ると、指定された閾値(71680MB)より空き領域が少なくなっていることで古い録画データが削除されているみたいですね。
ディスクの空き容量を確認してみてはいかがでしょう？

該当ログはこのあたり
```
[2022-03-25T18:19:48.684] [INFO] system - run storage limit cmd: remove
[2022-03-25T18:19:48.685] [ERROR] system - limit cmd error: remove
[2022-03-25T18:19:48.685] [ERROR] system - Error: CmdBinIsNotFound
at Object.ProcessUtil.parseCmdStr (/app/dist/util/util/ProcessUtil.ts:64:19)
at StorageManageModel. (/app/dist/model/operator/storage/model/operator/storage/StorageManageModel.ts:97:46)
at Generator.next ()
at fulfilled (/app/dist/model/operator/storage/StorageManageModel.js:17:58)
[2022-03-25T18:19:48.690] [INFO] system - name: recorded, free: 71617.65625, threshold: 71680
[2022-03-25T18:19:48.706] [INFO] system - storage limit remove recorded: 160235
[2022-03-25T18:19:48.707] [INFO] system - delete recorded: 160235
```

関連する設定項目はこちら
https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#recorded

**Comment by MicotoTisaki** [comment]
コメントありがとうございます。こちらの設定はかなり昔に適用し、70GB/42TBを切った場合に古いものから消していく様にしています。以前まではこの設定で1か月分はm2tsで問題なく保存され、新しいものが入るタイミングで古いものが正常に消えて行っている状態でした。ただ今回、m2tsファイルは正常に保存されているのに録画済みタブから閲覧ができないといった状態になっています。フォルダ直下は以下のようになっています。
![4](https://user-images.githubusercontent.com/32149435/160236338-751d11f7-635d-43a8-886e-372c3a809aac.PNG)
たぶん問題はdb側かそれを読み込むあたりに問題が発生していると思われるのですが、確認方法が分からず困っている状態です。

**Comment by l3tnun** [comment]
貼られているログからは、ストレージが足りずに録画が削除されていること、limitCmdが正しく設定できていないことくらいしかわかりません。
DBの破損等、色々原因があるかもしれませんが、私の方でのサポートしかねますのでクローズさせていただきます。
