### ISSUE TITLE
node.js 16.14.2環境で起動できない

### ISSUE THREAD

**Issue by admkazuya001** [l3tnun/EPGStation#590]
### 環境
* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.9.2-rc2`
* Version of Node: `v16.14.2`
* Version of NPM: `8.5.0`
* OS:CentOS Stream 8
* Architecture: x64

### Issue
対象ディレクトリでgit pull実行後、npm run all-install、npm run buildを実行した（正常終了を確認）
その後、pm2 restart epgstationを実行すると、数秒でstatusがerrorとなってしまう。
ログファイルには、以下のメッセージが大量に出力されている。

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/work/EPGStation/node_modules/url-join/lib/url-join.js from /root/work/EPGStation/dist/model/api/ApiUtil.js not supported.
Instead change the require of url-join.js in /root/work/EPGStation/dist/model/api/ApiUtil.js to a dynamic import() which is available in all CommonJS modules.
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at Object.<anonymous> (/root/work/EPGStation/dist/model/api/ApiUtil.js:54:17)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at Object.<anonymous> (/root/work/EPGStation/dist/model/ModelContainerSetter.js:7:35)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at Object.<anonymous> (/root/work/EPGStation/dist/index.js:43:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23) {
  code: 'ERR_REQUIRE_ESM'

**Comment by admkazuya001** [comment]
npm run build では、以下のようなエラーが出ていました。

[12:03:33] Starting '<anonymous>'...
src/model/api/ApiUtil.ts(24,25): error TS2349: This expression is not callable.
  Type 'typeof import("/root/work/EPGStation/node_modules/url-join/lib/url-join")' has no call signatures.
src/model/api/video/VideoApiModel.ts(61,37): error TS2339: Property 'fromFile' does not exist on type 'typeof import("/root/work/EPGStation/node_modules/file-type/index")'.
TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)
[12:03:37] Plumber found unhandled error:
 Error: TypeScript: Compilation failed

**Comment by l3tnun** [comment]
version 2.7.0で node.js v18に対応するにあたり解消されるかもしれません、
それまではdockerを使用してください。
