### ISSUE TITLE
録画後にブラウザで番組が再生できない

### ISSUE THREAD

**Issue by tsutaka** [l3tnun/EPGStation#599]
### 環境
* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.8.0`
* Version of Node: `16.13.1`
* Version of NPM: `8.1.2`
* OS: Ubuntu22.04
* Architecture: x64

* Version of ffmpeg: 4.2.4
* Tuner Card: PX-MLT8PE
* Docker image: docker-mirakurun-epgstation

### Issue
番組表から予約録画(mp4/ts削除)をした後に「録画済み」に番組が追加されたことを確認し、ブラウザで再生（「Play」「H.264」を選択）をしましたが再生できませんでした。ブラウザコンソールには以下のエラーメッセージが出力されています。

```ブラウザコンソール
GET http://localhost:8888/api/videos/4
500 Internal Server Error
```

/app/recordedのmp4ファイルを確認したところ、番組名のファイルはあるもののサイズが0のファイルでした。録画自体がうまくできなかったと想定しているのですが、それ以上の原因調査方法が分からず困っています。
心当たりの確認箇所などがありましたらご教示いただけますでしょうか。

docker logsおよびencode.logを下記に添付いたします。
他に必要なログ等がありましたらご連絡ください。
サムネイル作成も失敗していますが、もとの映像ファイルがないためではと考えています。

docker logs
```
[2022-04-30T08:00:01.671] [INFO] system - start recEnd reserveId: 3 recordedId: 2
[2022-04-30T08:00:01.673] [INFO] system - remove recording flag: 2
[2022-04-30T08:00:01.703] [INFO] system - update file size: 2
[2022-04-30T08:00:01.732] [INFO] system - emit finish recording reserveId: 3, recordedId: 2, isNeedDeleteReservation: true
[2022-04-30T08:00:01.733] [INFO] system - add thumbnail queue: 2
[2022-04-30T08:00:01.734] [INFO] system - recording finish reserveId: 3, recordedId: 2, videoFileFulPath: /app/recorded/2022年04月30日05時30分00秒-XXXX[字][デ].m2ts
[2022-04-30T08:00:01.734] [INFO] system - cancel reservation: 3
[2022-04-30T08:00:01.757] [INFO] system - { insert: 0, update: 0, delete: 1 }
[2022-04-30T08:00:01.767] [INFO] system - successful cancel reservation: 3
[2022-04-30T08:01:39.774] [ERROR] system - create thumbnail cmd error: 1
[2022-04-30T08:01:39.968] [ERROR] system - create thumbnail error: 2
[2022-04-30T08:01:39.969] [ERROR] system - Error: CreateThumbnailExitError
    at ThumbnailManageModel.<anonymous> (/app/dist/model/operator/thumbnail/model/operator/thumbnail/ThumbnailManageModel.ts:159:28)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/model/operator/thumbnail/ThumbnailManageModel.js:36:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-04-30T08:02:18.657] [INFO] system - add video file: 2 2022年04月30日05時30分00秒-XXXX[字][デ].mp4
[2022-04-30T08:02:18.878] [INFO] system - delete video file: 2
[2022-04-30T08:02:19.000] [INFO] system - delete: /app/recorded/2022年04月30日05時30分00秒-XXXX字][デ].m2ts
[2022-04-30T08:02:20.313] [INFO] system - encodingFinishCommand: undefined
```

/app/logs/Service/encode.log
```
2022-04-30T08:00:01.734] [INFO] encode - add new encode: 2
[2022-04-30T08:00:01.745] [INFO] encode - encode start. mode: H.264 name: XXXX[字][デ] file: /app/recorded/2022年04月30日05時30分00秒-XXXX[字][デ].m2ts -> /app/recorded/2022年04月30日05時30分00秒-XXXX[字][デ].mp4
[2022-04-30T08:00:01.745] [INFO] encode - encodeId: 2
[2022-04-30T08:00:01.745] [INFO] encode - encodeCmd.suffix: .mp4
[2022-04-30T08:00:01.745] [INFO] encode - queueItem.directory: undefined
[2022-04-30T08:00:01.745] [INFO] encode - outputFilePath: /app/recorded/2022年04月30日05時30分00秒-XXXX[字][デ].mp4
[2022-04-30T08:00:01.753] [INFO] encode - create new encode process: 1651273201753
[2022-04-30T08:02:18.559] [INFO] encode - exit code: 0, signal: null
[2022-04-30T08:02:18.598] [INFO] encode - Successfully encod: 2 /app/recorded/2022年04月30日05時30分00秒-XXXX[字][デ].mp4
```

/epgstation/config/config.yml抜粋
```
thumbnail: '%ROOT%/thumbnail'
thumbnailSize: 480x270
thumbnailPosition: 5

ffmpeg: /usr/local/bin/ffmpeg
ffprobe: /usr/local/bin/ffprobe
```

**Comment by tobitti0** [comment]
元データである`.m2ts`のサイズはどうでしょうか。
元データが正常ならば、エンコードに失敗しただけと思います。
エンコードに失敗する関連情報はいくつがあるので、過去Issueを見てみると良いと思います。
https://github.com/l3tnun/EPGStation/issues/583
など。

**Comment by tsutaka** [comment]
迅速なご回答ありがとうございます。
当初の録画はts削除にしていたため、再度tsありで録画をし確認しました。
`.m2ts`については容量は正常のようで、mp4は変わらず容量が0でした。
そのためエンコードに失敗しているだけのようです。

まずは、`.m2ts`の再生が問題なくできるのかを確認して、
いただいた関連チケットと合わせて確認をしてみようと思います。

**Comment by tsutaka** [comment]
【情報共有】
取得した`.m2ts`についてダウンロードしてVLCで再生したところ、
映像尺は想定通りあるのですが、映像音声ともに再生されませんでした。

ffprobeで`.m2ts`の情報を取得したところ、下記の通りでした。
arib_caption等の項目もあり、エンコードできない情報がtsに含まれていたために、
エンコードに失敗したのではないかと推測しています。
引き続きエンコード失敗の原因を調査します。
下記の映像情報で気になる点等がありましたらご指摘ください。

```
ffprobe version 4.4.1-3ubuntu5 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-18ubuntu1)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mpegts @ 0x562b519a5ec0] start time for stream 0 is not set in estimate_timings_from_pts
[mpegts @ 0x562b519a5ec0] start time for stream 1 is not set in estimate_timings_from_pts
[mpegts @ 0x562b519a5ec0] start time for stream 2 is not set in estimate_timings_from_pts
[mpegts @ 0x562b519a5ec0] start time for stream 4 is not set in estimate_timings_from_pts
[mpegts @ 0x562b519a5ec0] stream 1 : no TS found at start of file, duration not set
[mpegts @ 0x562b519a5ec0] stream 2 : no TS found at start of file, duration not set
[mpegts @ 0x562b519a5ec0] stream 12 : no TS found at start of file, duration not set
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 1 (Video: mpeg2video ([2][0][0][0] / 0x0002), none(tv)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 2 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 5 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 6 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 7 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 8 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 9 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 10 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 11 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 0x562b519a5ec0] Could not find codec parameters for stream 12 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mpegts, from '2022年04月30日12時15分00秒XXXX[字].m2ts':
  Duration: 00:04:53.46, start: 89675.649322, bitrate: 15519 kb/s
  Program 1024 
    Metadata:
      service_name    : ?NHK?Am9g?1�?El5~
      service_provider: 
  Stream #0:1[0x100]: Video: mpeg2video ([2][0][0][0] / 0x0002), none(tv), 90k tbr, 90k tbn, 90k tbc
  Stream #0:2[0x110]: Audio: aac ([15][0][0][0] / 0x000F), 0 channels
  Stream #0:3[0x130]: Subtitle: arib_caption (Profile A) ([6][0][0][0] / 0x0006)
  Stream #0:4[0x138]: Data: bin_data ([6][0][0][0] / 0x0006)
  Stream #0:5[0x140]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:6[0x160]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:7[0x161]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:8[0x162]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:9[0x170]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:10[0x171]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:11[0x172]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:12[0x111]: Audio: aac ([15][0][0][0] / 0x000F), 0 channels
  Program 1025 
    Metadata:
      service_name    : ?NHK?Am9g?2�?El5~
      service_provider: 
  Program 1408 
    Metadata:
      service_name    : ?NHK?7HBS?G�?El5~
      service_provider: 
  No Program
  Stream #0:0[0x12]: Data: epg
Unsupported codec with id 98306 for input stream 0
Unsupported codec with id 96272 for input stream 3
Unsupported codec with id 100359 for input stream 4
Unsupported codec with id 0 for input stream 5
Unsupported codec with id 0 for input stream 6
Unsupported codec with id 0 for input stream 7
Unsupported codec with id 0 for input stream 8
Unsupported codec with id 0 for input stream 9
Unsupported codec with id 0 for input stream 10
Unsupported codec with id 0 for input stream 11

```

**Comment by tobitti0** [comment]
VLCで正常に再生できないのは元データが怪しい気もします。
過去にもサムネイル作成、エンコードがうまくいかないというのがありました。VLCでも再生できず、原因はスクランブルに関するものでした。
https://github.com/l3tnun/EPGStation/issues/516#issuecomment-898947150
ここにあるように`tsselect`等を用いて元データが問題ないか確認したほうが良いと思います。

**Comment by tsutaka** [comment]
【情報共有】
tsselectで`.m2ts`ファイルを確認したところ下記で、
スクランブル解除されていないデータが結構あるように見受けられました。

```
pid=0x0000, total=    2944, d=  0, e=  0, scrambling=0, offset=161116
pid=0x0001, total=      30, d=  0, e=  0, scrambling=0, offset=6267544
pid=0x0010, total=     295, d=  0, e=  0, scrambling=0, offset=475828
pid=0x0011, total=     147, d=  0, e=  0, scrambling=0, offset=384836
pid=0x0012, total=   14930, d=  0, e=  0, scrambling=0, offset=123516
pid=0x0014, total=      59, d=  0, e=  0, scrambling=0, offset=1039640
pid=0x0023, total=       1, d=  0, e=  0, scrambling=0, offset=339738372
pid=0x0024, total=     294, d=  0, e=  0, scrambling=0, offset=1361684
pid=0x0028, total=       5, d=  0, e=  0, scrambling=0, offset=341129384
pid=0x0029, total=      10, d=  0, e=  0, scrambling=0, offset=99340328
pid=0x0100, total= 2637595, d=  0, e=  0, scrambling=2637595, offset=0
pid=0x0110, total=   27503, d=  0, e=  0, scrambling=27503, offset=11844
pid=0x0111, total=     108, d=  0, e=  0, scrambling=108, offset=567793652
pid=0x0130, total=     399, d=  0, e=  0, scrambling=0, offset=1657596
pid=0x0138, total=     292, d=  0, e=  0, scrambling=0, offset=831712
pid=0x0140, total=   44071, d=  0, e=  0, scrambling=44071, offset=4324
pid=0x0160, total=  175719, d=  0, e=  0, scrambling=175719, offset=752
pid=0x0161, total=   15565, d=  0, e=  0, scrambling=15565, offset=33652
pid=0x0162, total=   23991, d=  0, e=  0, scrambling=23991, offset=6768
pid=0x0170, total=   55167, d=  0, e=  0, scrambling=55167, offset=9588
pid=0x0171, total=   14791, d=  0, e=  0, scrambling=14791, offset=9212
pid=0x0172, total=     547, d=  0, e=  0, scrambling=547, offset=95692
pid=0x01f0, total=    5886, d=  0, e=  0, scrambling=0, offset=180668
pid=0x01ff, total=    4938, d=  0, e=  0, scrambling=0, offset=111860
pid=0x0901, total=    2943, d=  0, e=  0, scrambling=0, offset=181608
```

現状は拡張カード「PX-MLT8PE」にBCASを差していますが、
外部カードリーダもあるのでそちらにBCASを装着して、
スクランブル状態が変わるか状況を確認してみます。

**Comment by tsutaka** [comment]
事象解消しました。
@tobitti0 さんご指摘のとおりスクランブル解除ができていませんでした。
こちらの環境構築ミスでお騒がせしてしまいすみませんでした。
適切なアドバイスで迅速に事象解消まで対応できました。
改めまして、@tobitti0 さんには感謝申し上げます。

【原因概要】
* BCASによるスクランブル解除ができていませんでした
* そのため`.m2ts`が再生できず、サムネイルも作成できない状況でした

【対応内容】
* PX-MLT8PEに装着していたBCASを、カードリーダーSCR3310に装着変更
* 上記対応でスクランブルが適切に解除され事象解消を確認

【参考：調査経緯】
* `.m2ts`がVLCで、映像長はあるものの音声映像を見られないことを確認
* `.m2ts`がtsselectでスクランブル化されていることを確認
* BCAS内蔵のPX-MLT8PEにBCASを装着していた
* Linuxではチューナー内蔵型は使えないらしいとの情報を確認
  *  https://komone-life.com/2020/03/26/how-to-install-epgstation-docker-bcas/
  * `Linuxだとpx-w3u4内臓のカードリーダーが使えないので別途カードリーダを準備します。`
  * USB外付けのカードリーダーSCR3310にBCAS装着変更
* `lsusb`でカードリーダー接続を確認。以下3点は注意ポイント
  * BCAS差し込みは端子面を機器上方に向けて差し込む
  * USBポートによって認識しない場合がある
  * `lsusb`コマンドで確認したベンダID、プロダクトID、名称を`/etc/libccid_Info.plist`に追記する必要あり
* `pcsc_scan`コマンドでBCASカード認識を確認
* 録画ファイルの`.m2ts`をtsselectで確認し、すべての項目でスクランブルが0になっていることを確認
* ライブ視聴・録画でTS/H264で問題なく再生できることを確認

完全に余談ですが、
EPGStationでTSファイルにスクランブル情報を検知できた場合に、
WebGUI上に「スクランブル未解除」等の表示がされると
不具合時の原因切り分けがしやすく素敵だなぁ・・・と思いました。
実装はとても大変だと思いますので、あくまで個人の感想です。

今回初めてEPGStationの環境構築をしましたが、コンテナ化もされており今回事象以外は詰まることなく構築できました。また、EPGStation自体も使い勝手もよく素晴らしいアプリケーションだと思います。開発者様、メンテナ様には重ねて感謝申し上げます。

ではでは、失礼いたしました。
