### ISSUE TITLE
データベースの変更ができません

### ISSUE THREAD

**Issue by YMYAYA** [l3tnun/EPGStation#626]
* Version of EPGStation: 2.6.20
* Version of Mirakurun: 3.9.0-rc.2
* Version of Node: v14.21.1
* Version of NPM: 6.14.17
* OS: Centos7
* MariaDB: 10.6.11-MariaDB

上記の環境でEPGStationをインストールしました。
config/config.ymlでデータベースを初期設定のままにすると問題なくEpgstationが起動します。

*********************************
dbtype: sqlite
＃ sqlite:
＃  extensions:
＃   - '/hoge/regexp.dylib'
＃ regexp: true
*********************************

MariaDBをインストールし、データベース "epgstation"を作成してパスワード: " epgstation"、 grantの設定も行いました。
その後、mysqlを使用するためconfig/config.ymlのsqliteをコメントアウトし、mysqlに設定しました。

*********************************
＃dbtype: sqlite
＃ sqlite:
＃  extensions:
＃   - '/hoge/regexp.dylib'
＃ 　regexp: true

dbtype: mysql
mysql:
    host: localhost
    port: 3306
    user: epgstation
    password: epgstation
    database: epgstation
    charset: utf8mb4
*********************************

この後Epgstationを起動しようとするも起動できません。
エラーメッセージは以下です

*********************************
> node dist/index.js

initialize error
YAMLException: bad indentation of a mapping entry (10:2)

  7 | #     - '/hoge/regexp.dylib'
  8 | #   regexp: true
  9 |
 10 |  dbtype: mysql
-------^
 11 |  mysql:
 12 |      host: localhost
    at generateError (/home/xxxx/EPGStation/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/home/xxxx/EPGStation/node_modules/js-yaml/lib/loader.js:187:9)
    at readBlockMapping (/home/xxxx/EPGStation/node_modules/js-yaml/lib/loader.js:1182:7)
    at composeNode (/home/xxxx/EPGStation/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/home/xxxx/EPGStation/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/home/xxxx/EPGStation/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/home/xxxx/EPGStation/node_modules/js-yaml/lib/loader.js:1714:19)
    at Configuration.readConfig (/home/xxxx/EPGStation/dist/model/model/Configuration.ts:80:50)
    at new Configuration (/home/xxxx/EPGStation/dist/model/model/Configuration.ts:30:28)
    at _createInstance (/home/xxxx/EPGStation/node_modules/inversify/src/resolution/instantiation.ts:33:5) {
  reason: 'bad indentation of a mapping entry',
...
...
...

**Comment by l3tnun** [comment]
ご自身で原因を調査してください。ここはサポートする場ではありません。
