### ISSUE TITLE
EPGUpdater で TypeORMError がスローされる

### ISSUE THREAD

**Issue by hiroxto** [l3tnun/EPGStation#687]
### 環境
* Version of EPGStation: `2.10.0`
* Version of Mirakurun: `3.8.0`
* Version of Node: `18.20.3`
* Version of NPM: `10.7.0`
* OS: Ubuntu 24.04
* Architecture: x64

`l3tnun/epgstation:v2.10.0-debian` がベースの Docker 上で動いています

### Issue

定期的に EPGUpdater で `TypeORMError: Empty criteria(s) are not allowed for the delete method.` がスローされエラーログが記録されます。

エラーログの記録箇所は `src/model/db/ProgramDB.ts` の `ProgramDB.update()` と思われますが，発生条件などは調査できていません。

https://github.com/l3tnun/EPGStation/blob/5cf2ea383d37937eacecf424820dbd7a278d577e/src/model/db/ProgramDB.ts#L320-L323

ログの記録を始めたのがここ最近のため古いログは残っておらず，いつから発生しているのかは不明ですが，記録を開始した 2024/06/24 から同じ内容のエラーログが記録されていました
- 少なくとも `v2.9.1` を使っている頃から発生しており，`v2.10.0` に更新しても変わらず発生します

エラー発生時の周辺のログ (`logs/EPGUpdater/system.log` info 以上のログのみ)

```log
[2024-07-04T16:35:20.321] [INFO] system - update program db start
[2024-07-04T16:35:20.322] [INFO] system - { deleteValues: 2, insertValues: 0, updateValues: 124 }
[2024-07-04T16:35:20.332] [ERROR] system - program delete error: undefined
[2024-07-04T16:35:20.332] [ERROR] system - TypeORMError: Empty criteria(s) are not allowed for the delete method.
    at EntityManager.delete (/app/node_modules/typeorm/entity-manager/EntityManager.js:366:35)
    at ProgramDB.update (/app/dist/model/db/ProgramDB.js:252:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EPGUpdateManageModel.saveProgram (/app/dist/model/epgUpdater/EPGUpdateManageModel.js:433:21)
    at async EPGUpdater.updateMirakurunEventStream (/app/dist/model/epgUpdater/EPGUpdater.js:138:13)
[2024-07-04T16:35:20.333] [ERROR] system - program delete error: undefined
[2024-07-04T16:35:20.333] [ERROR] system - TypeORMError: Empty criteria(s) are not allowed for the delete method.
    at EntityManager.delete (/app/node_modules/typeorm/entity-manager/EntityManager.js:366:35)
    at ProgramDB.update (/app/dist/model/db/ProgramDB.js:252:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EPGUpdateManageModel.saveProgram (/app/dist/model/epgUpdater/EPGUpdateManageModel.js:433:21)
    at async EPGUpdater.updateMirakurunEventStream (/app/dist/model/epgUpdater/EPGUpdater.js:138:13)
[2024-07-04T16:35:20.489] [INFO] system - update program db done
[2024-07-04T16:41:20.467] [INFO] system - delete old program db start
[2024-07-04T16:41:20.486] [INFO] system - delete old program db done
[2024-07-04T16:41:20.531] [INFO] system - update channel db start
[2024-07-04T16:41:20.531] [INFO] system - { insertValues: 0, updateValues: 7 }
[2024-07-04T16:41:20.544] [INFO] system - update channel db done
[2024-07-04T16:41:20.545] [INFO] system - update program db start
[2024-07-04T16:41:20.545] [INFO] system - { deleteValues: 1, insertValues: 0, updateValues: 300 }
[2024-07-04T16:41:20.558] [ERROR] system - program delete error: undefined
[2024-07-04T16:41:20.558] [ERROR] system - TypeORMError: Empty criteria(s) are not allowed for the delete method.
    at EntityManager.delete (/app/node_modules/typeorm/entity-manager/EntityManager.js:366:35)
    at ProgramDB.update (/app/dist/model/db/ProgramDB.js:252:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EPGUpdateManageModel.saveProgram (/app/dist/model/epgUpdater/EPGUpdateManageModel.js:433:21)
    at async EPGUpdater.updateMirakurunEventStream (/app/dist/model/epgUpdater/EPGUpdater.js:149:13)
[2024-07-04T16:41:20.906] [INFO] system - update program db done
[2024-07-04T16:51:20.694] [INFO] system - delete old program db start
[2024-07-04T16:51:20.722] [INFO] system - delete old program db done
[2024-07-04T17:01:10.860] [INFO] system - update program db start
```

**Comment by scimmia9286** [comment]
以前同様のログ発生原因を調査したことがあります。
全く同じ原因かどうかはわかりませんが、私の場合はEPGStationが保持していないプログラムの削除電文がMirakurunから来ていました。
保持していないのでdeleteできなくても問題ないため放置しています。
