### ISSUE TITLE
reserves.json parse error

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#97]
お世話になっております。EPGStation、便利に使わせてもらっています。

本日ふと立ち上げてみると、普段見えているはずのGR/BS/CSのタブが消えていました。
取り合えず再起動してみたところサービスのEPGSTATIONが開始途中で停止してしまいます。

管理者権限のPowerShellにて起動させようとすると表題の通り”reserves.json parse error”と出て起動が止まります。

・Mirakurunは動作している（TVTestで動作を確認）
・録画先HDDは壊れていない模様

この場合、再インストールで治りますでしょうか。バックアップが取れないので、不用意に弄るのが少々怖いです。

以下にPowershellの表示をコピペします。

[2018-06-10T20:41:24.514] [FATAL] system - SyntaxError: Unexpected token   in JSON at position 0
    at JSON.parse (<anonymous>)
    at ReservationManageModel.readReservesFile (C:\EPGStation\dist\server\Model\Operator\Reservation\ReservationManageModel.js:861:34)
    at new ReservationManageModel (C:\EPGStation\dist\server\Model\Operator\Reservation\ReservationManageModel.js:43:14)
    at Object.ModelFactorySetting.init (C:\EPGStation\dist\server\Model\MainModelFactorySetting.js:89:35)
    at Object.<anonymous> (C:\EPGStation\dist\server\index.js:46:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[2018-06-10T20:41:24.520] [FATAL] system - reserves.json parse error

お手数ですが、お知恵を拝借できますと幸いです。

**Comment by l3tnun** [comment]
reserves.json が壊れているのではないでしょうか？

手動予約の内容は消えますが reserves.json を削除すれば起動するはずです。

**Comment by ohmsa** [comment]
すみません、システムは
Windows 10 pro x64
Core i7 6700
メモリ16GB×2
Intel  SSDPEKKW512G8XT
WD RED 8TB
PX-Q3PE

node 8.11.2
winser 1.0.3
Mirakurun 2.7.0
です。

**Comment by ohmsa** [comment]
早速の返信ありがとうございます。試してみます

**Comment by l3tnun** [comment]
もしかしたらアクセス権限の関係で reserves.json が読めないのかもしれないですね。
https://jsonlint.com/ 等で json が正しく生成されているか確認するといいかもしれません。

**Comment by ohmsa** [comment]
reservers.jsonをリネームしたところサービスが起動するようになりました。助かりました。

大変ありがとうございます。
